"""OpenFOAM case setup for turbomachinery simulations.

Generates the directory structure and configuration files needed to
run a turbomachinery CFD simulation in OpenFOAM.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, TextIO


# ── Standard extra patches for turbomachinery meshes ──
# These are patches created by blockMesh that the BC writers must include.
# Each entry: (patch_name, openfoam_bc_type)

_EXTRA_PATCHES = [
    ("periodic_upper", "cyclic"),
    ("periodic_lower", "cyclic"),
    ("frontAndBack", "empty"),
    ("defaultFaces", "empty"),
]


def _write_extra_patches(f: TextIO) -> None:
    """Write BC entries for cyclic, empty, and default patches.

    These patches are generated by blockMesh from the AstraTurbo
    multi-block mesh but are not part of the core 5-patch set
    (inlet, outlet, blade, hub, shroud).

    BC type must match mesh patch type for cyclic and empty patches.
    """
    for name, bc_type in _EXTRA_PATCHES:
        # cyclic and empty must match the mesh patch type exactly
        f.write(f"    {name} {{ type {bc_type}; }}\n")


def create_openfoam_case(
    case_dir: str | Path,
    mesh_format: str = "blockMesh",
    turbulence_model: str = "kOmegaSST",
    solver: str = "simpleFoam",
    inlet_velocity: float = 100.0,
    outlet_pressure: float = 101325.0,
    density: float = 1.225,
    viscosity: float = 1.8e-5,
    patch_names: dict[str, str] | None = None,
    compressible: bool = False,
    total_pressure: float = 101325.0,
    total_temperature: float = 288.15,
) -> Path:
    """Create an OpenFOAM case directory with turbomachinery setup.

    Args:
        case_dir: Path for the case directory.
        mesh_format: 'blockMesh' or 'cgns' (for cgnsToFoam).
        turbulence_model: Turbulence model name.
        solver: OpenFOAM solver name.
        inlet_velocity: Inlet velocity magnitude (m/s).
        outlet_pressure: Outlet static pressure (Pa).
        density: Fluid density (kg/m^3).
        viscosity: Kinematic viscosity (m^2/s).
        patch_names: Mapping of logical names to actual mesh patch names.
        compressible: If True, write compressible BCs and thermophysical properties.
        total_pressure: Total pressure at inlet (Pa), used when compressible=True.
        total_temperature: Total temperature at inlet (K), used when compressible=True.

    Returns:
        Path to the created case directory.
    """
    case_dir = Path(case_dir)

    # Security: validate solver and turbulence model names
    _ALLOWED_SOLVERS = {
        "simpleFoam", "pimpleFoam", "rhoSimpleFoam", "rhoPimpleFoam",
        "sonicFoam", "compressibleInterFoam",
    }
    _ALLOWED_TURB = {
        "kOmegaSST", "kEpsilon", "SpalartAllmaras", "kOmega",
        "realizableKE", "LamBremhorstKE", "laminar",
    }
    if solver not in _ALLOWED_SOLVERS:
        raise ValueError(f"Invalid solver '{solver}'. Allowed: {_ALLOWED_SOLVERS}")
    if turbulence_model not in _ALLOWED_TURB:
        raise ValueError(f"Invalid turbulence model '{turbulence_model}'. Allowed: {_ALLOWED_TURB}")

    # Create directory structure
    (case_dir / "0").mkdir(parents=True, exist_ok=True)
    (case_dir / "constant" / "polyMesh").mkdir(parents=True, exist_ok=True)
    (case_dir / "system").mkdir(parents=True, exist_ok=True)

    # Default patch name mapping
    if patch_names is None:
        patch_names = {
            "inlet": "inlet",
            "outlet": "outlet",
            "blade": "blade",
            "hub": "hub",
            "shroud": "shroud",
            "periodic_upper": "periodic_upper",
            "periodic_lower": "periodic_lower",
        }

    # Write controlDict
    _write_control_dict(case_dir / "system" / "controlDict", solver)

    # Write fvSchemes
    _write_fv_schemes(case_dir / "system" / "fvSchemes", compressible=compressible)

    # Write fvSolution
    _write_fv_solution(case_dir / "system" / "fvSolution", solver)

    # Write transportProperties
    _write_transport_properties(
        case_dir / "constant" / "transportProperties", viscosity
    )

    # Write turbulenceProperties
    _write_turbulence_properties(
        case_dir / "constant" / "turbulenceProperties", turbulence_model
    )

    # Write boundary conditions (compressible vs incompressible)
    if compressible:
        _write_thermophysical_properties(case_dir / "constant" / "thermophysicalProperties")
        _write_compressible_velocity_bc(
            case_dir / "0" / "U", inlet_velocity, patch_names
        )
        _write_compressible_pressure_bc(
            case_dir / "0" / "p", total_pressure, outlet_pressure, patch_names
        )
        _write_temperature_bc(
            case_dir / "0" / "T", total_temperature, patch_names
        )
    else:
        _write_velocity_bc(case_dir / "0" / "U", inlet_velocity, patch_names)
        _write_pressure_bc(case_dir / "0" / "p", outlet_pressure, patch_names)

    # Write turbulence field files (required by all RANS models)
    if turbulence_model != "laminar":
        _write_turbulence_fields(case_dir / "0", inlet_velocity, compressible)

    return case_dir


def _write_foam_header(f, cls: str, obj: str) -> None:
    f.write("FoamFile\n{\n")
    f.write("    version     2.0;\n")
    f.write("    format      ascii;\n")
    f.write(f"    class       {cls};\n")
    f.write(f'    object      {obj};\n')
    f.write("}\n\n")


def _write_control_dict(filepath: Path, solver: str) -> None:
    with open(filepath, "w") as f:
        _write_foam_header(f, "dictionary", "controlDict")
        f.write(f'application     {solver};\n\n')
        f.write("startFrom       startTime;\n")
        f.write("startTime       0;\n")
        f.write("stopAt          endTime;\n")
        f.write("endTime         1000;\n")
        f.write("deltaT          1;\n")
        f.write("writeControl    timeStep;\n")
        f.write("writeInterval   100;\n")
        f.write("purgeWrite      3;\n")
        f.write("writeFormat     ascii;\n")
        f.write("writePrecision  8;\n")
        f.write("writeCompression off;\n")
        f.write("timeFormat      general;\n")
        f.write("timePrecision   6;\n")
        f.write("runTimeModifiable true;\n")


def _write_fv_schemes(filepath: Path, compressible: bool = False, is_rotating: bool = False) -> None:
    with open(filepath, "w") as f:
        _write_foam_header(f, "dictionary", "fvSchemes")
        f.write("ddtSchemes { default steadyState; }\n")
        f.write("gradSchemes { default Gauss linear; }\n")
        f.write("divSchemes\n{\n")
        f.write("    default bounded Gauss upwind;\n")
        f.write("    div(phi,U) bounded Gauss linearUpwind grad(U);\n")
        f.write("    div(phi,k) bounded Gauss upwind;\n")
        f.write("    div(phi,omega) bounded Gauss upwind;\n")
        if compressible:
            f.write("    div(phi,e) bounded Gauss upwind;\n")
            f.write("    div(phi,K) bounded Gauss upwind;\n")
            f.write("    div(phid,p) Gauss upwind;\n")
            f.write("    div(phi,Ekp) bounded Gauss upwind;\n")
            f.write("    div(((rho*nuEff)*dev2(T(grad(U))))) Gauss linear;\n")
        else:
            f.write("    div((nuEff*dev2(T(grad(U))))) Gauss linear;\n")
        # MRF requires additional divergence schemes
        if is_rotating and compressible:
            f.write("    div(phiMRF,p) Gauss upwind;\n")
            f.write("    div(phiMRF,U) Gauss upwind;\n")
        f.write("}\n")
        f.write("laplacianSchemes { default Gauss linear corrected; }\n")
        f.write("interpolationSchemes { default linear; }\n")
        f.write("snGradSchemes { default corrected; }\n")
        f.write("wallDist { method meshWave; }\n")


def _write_fv_solution(filepath: Path, solver: str) -> None:
    is_compressible = solver.startswith("rho") or solver == "sonicFoam"
    with open(filepath, "w") as f:
        _write_foam_header(f, "dictionary", "fvSolution")
        f.write("solvers\n{\n")
        f.write("    p { solver GAMG; tolerance 1e-06; relTol 0.1;\n")
        f.write("        smoother GaussSeidel; }\n")
        f.write("    U { solver smoothSolver; smoother GaussSeidel;\n")
        f.write("        tolerance 1e-06; relTol 0.1; }\n")
        f.write("    k { solver smoothSolver; smoother GaussSeidel;\n")
        f.write("        tolerance 1e-06; relTol 0.1; }\n")
        f.write("    omega { solver smoothSolver; smoother GaussSeidel;\n")
        f.write("        tolerance 1e-06; relTol 0.1; }\n")
        if is_compressible:
            f.write("    e { solver smoothSolver; smoother GaussSeidel;\n")
            f.write("        tolerance 1e-06; relTol 0.1; }\n")
            f.write('    "rho.*" { solver PCG; preconditioner DIC;\n')
            f.write("        tolerance 1e-06; relTol 0.1; }\n")
        f.write("}\n\n")
        f.write("SIMPLE\n{\n")
        f.write("    nNonOrthogonalCorrectors 0;\n")
        f.write("    pRefCell 0;\n")
        f.write("    pRefValue 0;\n")
        if is_compressible:
            f.write("    residualControl { p 1e-4; U 1e-4; e 1e-4; k 1e-4; omega 1e-4; }\n")
        else:
            f.write("    residualControl { p 1e-4; U 1e-4; k 1e-4; omega 1e-4; }\n")
        f.write("}\n\n")
        f.write("relaxationFactors\n{\n")
        f.write("    fields { p 0.3; rho 0.5; }\n")
        if is_compressible:
            f.write("    equations { U 0.7; e 0.5; k 0.7; omega 0.7; }\n")
        else:
            f.write("    equations { U 0.7; k 0.7; omega 0.7; }\n")
        f.write("}\n")


def _write_transport_properties(filepath: Path, viscosity: float) -> None:
    with open(filepath, "w") as f:
        _write_foam_header(f, "dictionary", "transportProperties")
        f.write(f"nu              [0 2 -1 0 0 0 0] {viscosity:.6e};\n")


def _write_turbulence_properties(filepath: Path, model: str) -> None:
    with open(filepath, "w") as f:
        _write_foam_header(f, "dictionary", "turbulenceProperties")
        f.write("simulationType RAS;\n\n")
        f.write("RAS\n{\n")
        f.write(f"    RASModel    {model};\n")
        f.write("    turbulence  on;\n")
        f.write("    printCoeffs on;\n")
        f.write("}\n")


def _write_velocity_bc(
    filepath: Path, velocity: float, patch_names: dict[str, str] | None = None,
) -> None:
    if patch_names is None:
        patch_names = {"inlet": "inlet", "outlet": "outlet", "blade": "blade",
                       "hub": "hub", "shroud": "shroud"}
    with open(filepath, "w") as f:
        _write_foam_header(f, "volVectorField", "U")
        f.write("dimensions      [0 1 -1 0 0 0 0];\n\n")
        f.write(f"internalField   uniform ({velocity} 0 0);\n\n")
        f.write("boundaryField\n{\n")
        f.write(f"    {patch_names.get('inlet', 'inlet')} {{ type fixedValue; value uniform ({velocity} 0 0); }}\n")
        f.write(f"    {patch_names.get('outlet', 'outlet')} {{ type zeroGradient; }}\n")
        f.write(f"    {patch_names.get('blade', 'blade')} {{ type noSlip; }}\n")
        f.write(f"    {patch_names.get('hub', 'hub')} {{ type noSlip; }}\n")
        f.write(f"    {patch_names.get('shroud', 'shroud')} {{ type noSlip; }}\n")
        _write_extra_patches(f)
        f.write("}\n")


def _write_pressure_bc(
    filepath: Path, pressure: float, patch_names: dict[str, str] | None = None,
) -> None:
    if patch_names is None:
        patch_names = {"inlet": "inlet", "outlet": "outlet", "blade": "blade",
                       "hub": "hub", "shroud": "shroud"}
    with open(filepath, "w") as f:
        _write_foam_header(f, "volScalarField", "p")
        f.write("dimensions      [0 2 -2 0 0 0 0];\n\n")
        f.write("internalField   uniform 0;\n\n")
        f.write("boundaryField\n{\n")
        f.write(f"    {patch_names.get('inlet', 'inlet')} {{ type zeroGradient; }}\n")
        f.write(f"    {patch_names.get('outlet', 'outlet')} {{ type fixedValue; value uniform 0; }}\n")
        f.write(f"    {patch_names.get('blade', 'blade')} {{ type zeroGradient; }}\n")
        f.write(f"    {patch_names.get('hub', 'hub')} {{ type zeroGradient; }}\n")
        f.write(f"    {patch_names.get('shroud', 'shroud')} {{ type zeroGradient; }}\n")
        _write_extra_patches(f)
        f.write("}\n")


# ── Compressible BC writers ──────────────────────────────────

def _write_thermophysical_properties(filepath: Path) -> None:
    """Write thermophysicalProperties for ideal gas (perfect gas, Sutherland)."""
    with open(filepath, "w") as f:
        _write_foam_header(f, "dictionary", "thermophysicalProperties")
        f.write("thermoType\n{\n")
        f.write("    type            hePsiThermo;\n")
        f.write("    mixture         pureMixture;\n")
        f.write("    transport       sutherland;\n")
        f.write("    thermo          hConst;\n")
        f.write("    equationOfState perfectGas;\n")
        f.write("    specie          specie;\n")
        f.write("    energy          sensibleInternalEnergy;\n")
        f.write("}\n\n")
        f.write("mixture\n{\n")
        f.write("    specie { molWeight 28.96; }\n")
        f.write("    thermodynamics { Cp 1005; Hf 0; }\n")
        f.write("    transport { As 1.458e-06; Ts 110.4; }\n")
        f.write("}\n")


def _write_compressible_velocity_bc(
    filepath: Path, velocity: float, patch_names: dict[str, str] | None = None,
) -> None:
    """Write velocity BCs for compressible solver (pressureInletOutletVelocity at inlet)."""
    if patch_names is None:
        patch_names = {"inlet": "inlet", "outlet": "outlet", "blade": "blade",
                       "hub": "hub", "shroud": "shroud"}
    with open(filepath, "w") as f:
        _write_foam_header(f, "volVectorField", "U")
        f.write("dimensions      [0 1 -1 0 0 0 0];\n\n")
        f.write(f"internalField   uniform ({velocity} 0 0);\n\n")
        f.write("boundaryField\n{\n")
        f.write(f"    {patch_names.get('inlet', 'inlet')}\n    {{\n")
        f.write(f"        type    pressureInletOutletVelocity;\n")
        f.write(f"        value   uniform ({velocity} 0 0);\n    }}\n")
        f.write(f"    {patch_names.get('outlet', 'outlet')}\n    {{\n")
        f.write(f"        type    inletOutlet;\n")
        f.write(f"        inletValue uniform (0 0 0);\n")
        f.write(f"        value   uniform ({velocity} 0 0);\n    }}\n")
        f.write(f"    {patch_names.get('blade', 'blade')} {{ type noSlip; }}\n")
        f.write(f"    {patch_names.get('hub', 'hub')} {{ type noSlip; }}\n")
        f.write(f"    {patch_names.get('shroud', 'shroud')} {{ type noSlip; }}\n")
        _write_extra_patches(f)
        f.write("}\n")


def _write_compressible_pressure_bc(
    filepath: Path,
    total_pressure: float,
    outlet_pressure: float,
    patch_names: dict[str, str] | None = None,
) -> None:
    """Write pressure BCs for compressible solver (totalPressure at inlet, fixedValue at outlet)."""
    if patch_names is None:
        patch_names = {"inlet": "inlet", "outlet": "outlet", "blade": "blade",
                       "hub": "hub", "shroud": "shroud"}
    with open(filepath, "w") as f:
        _write_foam_header(f, "volScalarField", "p")
        f.write("dimensions      [1 -1 -2 0 0 0 0];\n\n")
        f.write(f"internalField   uniform {total_pressure};\n\n")
        f.write("boundaryField\n{\n")
        f.write(f"    {patch_names.get('inlet', 'inlet')}\n    {{\n")
        f.write(f"        type        totalPressure;\n")
        f.write(f"        p0          uniform {total_pressure};\n")
        f.write(f"        gamma       1.4;\n")
        f.write(f"        value       uniform {total_pressure};\n    }}\n")
        f.write(f"    {patch_names.get('outlet', 'outlet')}\n    {{\n")
        f.write(f"        type        fixedValue;\n")
        f.write(f"        value       uniform {outlet_pressure};\n    }}\n")
        f.write(f"    {patch_names.get('blade', 'blade')} {{ type zeroGradient; }}\n")
        f.write(f"    {patch_names.get('hub', 'hub')} {{ type zeroGradient; }}\n")
        f.write(f"    {patch_names.get('shroud', 'shroud')} {{ type zeroGradient; }}\n")
        _write_extra_patches(f)
        f.write("}\n")


def _write_temperature_bc(
    filepath: Path,
    total_temperature: float,
    patch_names: dict[str, str] | None = None,
) -> None:
    """Write temperature BCs (totalTemperature at inlet)."""
    if patch_names is None:
        patch_names = {"inlet": "inlet", "outlet": "outlet", "blade": "blade",
                       "hub": "hub", "shroud": "shroud"}
    with open(filepath, "w") as f:
        _write_foam_header(f, "volScalarField", "T")
        f.write("dimensions      [0 0 0 1 0 0 0];\n\n")
        f.write(f"internalField   uniform {total_temperature};\n\n")
        f.write("boundaryField\n{\n")
        f.write(f"    {patch_names.get('inlet', 'inlet')}\n    {{\n")
        f.write(f"        type        totalTemperature;\n")
        f.write(f"        T0          uniform {total_temperature};\n")
        f.write(f"        gamma       1.4;\n")
        f.write(f"        value       uniform {total_temperature};\n    }}\n")
        f.write(f"    {patch_names.get('outlet', 'outlet')}\n    {{\n")
        f.write(f"        type        inletOutlet;\n")
        f.write(f"        inletValue  uniform {total_temperature};\n")
        f.write(f"        value       uniform {total_temperature};\n    }}\n")
        f.write(f"    {patch_names.get('blade', 'blade')} {{ type zeroGradient; }}\n")
        f.write(f"    {patch_names.get('hub', 'hub')} {{ type zeroGradient; }}\n")
        f.write(f"    {patch_names.get('shroud', 'shroud')} {{ type zeroGradient; }}\n")
        _write_extra_patches(f)
        f.write("}\n")


def _write_turbulence_fields(
    zero_dir: Path, velocity: float, compressible: bool = False
) -> None:
    """Write k, omega, nut, and alphat field files for RANS turbulence models."""
    I = 0.05
    l = 0.01
    Cmu = 0.09
    k_val = max(1.5 * (I * velocity) ** 2, 0.1)
    omega_val = k_val ** 0.5 / (Cmu ** 0.25 * l)
    nut_val = k_val / omega_val if omega_val > 0 else 1e-5
    alphat_val = nut_val / 0.85

    with open(zero_dir / "k", "w") as f:
        _write_foam_header(f, "volScalarField", "k")
        f.write("dimensions      [0 2 -2 0 0 0 0];\n\n")
        f.write(f"internalField   uniform {k_val:.6g};\n\n")
        f.write("boundaryField\n{\n")
        f.write(f"    inlet {{ type fixedValue; value uniform {k_val:.6g}; }}\n")
        f.write(f"    outlet {{ type zeroGradient; }}\n")
        f.write(f"    blade {{ type kqRWallFunction; value uniform {k_val:.6g}; }}\n")
        f.write(f"    hub {{ type kqRWallFunction; value uniform {k_val:.6g}; }}\n")
        f.write(f"    shroud {{ type kqRWallFunction; value uniform {k_val:.6g}; }}\n")
        _write_extra_patches(f)
        f.write("}\n")

    with open(zero_dir / "omega", "w") as f:
        _write_foam_header(f, "volScalarField", "omega")
        f.write("dimensions      [0 0 -1 0 0 0 0];\n\n")
        f.write(f"internalField   uniform {omega_val:.6g};\n\n")
        f.write("boundaryField\n{\n")
        f.write(f"    inlet {{ type fixedValue; value uniform {omega_val:.6g}; }}\n")
        f.write(f"    outlet {{ type zeroGradient; }}\n")
        f.write(f"    blade {{ type omegaWallFunction; value uniform {omega_val:.6g}; }}\n")
        f.write(f"    hub {{ type omegaWallFunction; value uniform {omega_val:.6g}; }}\n")
        f.write(f"    shroud {{ type omegaWallFunction; value uniform {omega_val:.6g}; }}\n")
        _write_extra_patches(f)
        f.write("}\n")

    with open(zero_dir / "nut", "w") as f:
        _write_foam_header(f, "volScalarField", "nut")
        f.write("dimensions      [0 2 -1 0 0 0 0];\n\n")
        f.write(f"internalField   uniform {nut_val:.6g};\n\n")
        f.write("boundaryField\n{\n")
        f.write(f"    inlet {{ type calculated; value uniform {nut_val:.6g}; }}\n")
        f.write(f"    outlet {{ type calculated; value uniform {nut_val:.6g}; }}\n")
        f.write(f"    blade {{ type nutkWallFunction; value uniform 0; }}\n")
        f.write(f"    hub {{ type nutkWallFunction; value uniform 0; }}\n")
        f.write(f"    shroud {{ type nutkWallFunction; value uniform 0; }}\n")
        _write_extra_patches(f)
        f.write("}\n")

    if compressible:
        with open(zero_dir / "alphat", "w") as f:
            _write_foam_header(f, "volScalarField", "alphat")
            f.write("dimensions      [1 -1 -1 0 0 0 0];\n\n")
            f.write(f"internalField   uniform {alphat_val:.6g};\n\n")
            f.write("boundaryField\n{\n")
            f.write(f"    inlet {{ type calculated; value uniform {alphat_val:.6g}; }}\n")
            f.write(f"    outlet {{ type calculated; value uniform {alphat_val:.6g}; }}\n")
            f.write(f"    blade {{ type compressible::alphatWallFunction; Prt 0.85; value uniform 0; }}\n")
            f.write(f"    hub {{ type compressible::alphatWallFunction; Prt 0.85; value uniform 0; }}\n")
            f.write(f"    shroud {{ type compressible::alphatWallFunction; Prt 0.85; value uniform 0; }}\n")
            _write_extra_patches(f)
            f.write("}\n")


def write_simpleFoam_case(
    case_dir: str | Path,
    mesh,
    inlet_velocity: float = 150.0,
    n_iterations: int = 500,
    nu: float = 1.47e-5,
    turbulence_intensity: float = 0.05,
    length_scale: float = 0.01,
) -> Path:
    """Write a complete, self-consistent simpleFoam (incompressible) case.

    Creates all files from scratch with matching dimensions and BCs.
    No fixups needed — this is ready to run directly.

    Args:
        case_dir: Output directory for the OpenFOAM case.
        mesh: MultiBlockMesh to export as blockMeshDict.
        inlet_velocity: Inlet flow velocity (m/s).
        n_iterations: Maximum solver iterations.
        nu: Kinematic viscosity (m²/s).
        turbulence_intensity: Turbulence intensity fraction (e.g. 0.05 = 5%).
        length_scale: Turbulence length scale (m).

    Returns:
        Path to the case directory.
    """
    case_dir = Path(case_dir)
    (case_dir / "0").mkdir(parents=True, exist_ok=True)
    (case_dir / "constant").mkdir(exist_ok=True)
    (case_dir / "system").mkdir(exist_ok=True)

    # Turbulence field values
    Cmu = 0.09
    k_val = max(1.5 * (turbulence_intensity * inlet_velocity) ** 2, 0.1)
    omega_val = k_val ** 0.5 / (Cmu ** 0.25 * length_scale)
    nut_val = k_val / max(omega_val, 1e-10)

    # ── blockMeshDict ──
    mesh.export_openfoam(str(case_dir / "system" / "blockMeshDict"))

    # ── controlDict ──
    write_interval = max(n_iterations // 5, 50)
    (case_dir / "system" / "controlDict").write_text(
        "FoamFile { version 2.0; format ascii; class dictionary; object controlDict; }\n\n"
        "application     simpleFoam;\n"
        "startFrom       startTime;\n"
        "startTime       0;\n"
        "stopAt          endTime;\n"
        f"endTime         {n_iterations};\n"
        "deltaT          1;\n"
        "writeControl    timeStep;\n"
        f"writeInterval   {write_interval};\n"
        "purgeWrite      3;\n"
        "writeFormat     ascii;\n"
        "writePrecision  8;\n"
        "writeCompression off;\n"
        "timeFormat      general;\n"
        "timePrecision   6;\n"
        "runTimeModifiable true;\n"
    )

    # ── fvSchemes (production: bounded upwind for stability, linear for diffusion) ──
    (case_dir / "system" / "fvSchemes").write_text(
        "FoamFile { version 2.0; format ascii; class dictionary; object fvSchemes; }\n\n"
        "ddtSchemes { default steadyState; }\n"
        "gradSchemes { default Gauss linear; }\n"
        "divSchemes\n{\n"
        "    default         none;\n"
        "    div(phi,U)      bounded Gauss linearUpwind grad(U);\n"
        "    div(phi,k)      bounded Gauss upwind;\n"
        "    div(phi,omega)  bounded Gauss upwind;\n"
        "    div((nuEff*dev2(T(grad(U))))) Gauss linear;\n"
        "}\n"
        "laplacianSchemes { default Gauss linear corrected; }\n"
        "interpolationSchemes { default linear; }\n"
        "snGradSchemes { default corrected; }\n"
        "wallDist { method meshWave; }\n"
    )

    # ── fvSolution (conservative relaxation for coarse meshes) ──
    (case_dir / "system" / "fvSolution").write_text(
        "FoamFile { version 2.0; format ascii; class dictionary; object fvSolution; }\n\n"
        "solvers\n{\n"
        "    Phi\n    {\n"
        "        solver          GAMG;\n"
        "        smoother        GaussSeidel;\n"
        "        tolerance       1e-7;\n"
        "        relTol          0.01;\n"
        "    }\n"
        "    p\n    {\n"
        "        solver          GAMG;\n"
        "        smoother        GaussSeidel;\n"
        "        tolerance       1e-7;\n"
        "        relTol          0.01;\n"
        "    }\n"
        "    \"(U|k|omega)\"\n    {\n"
        "        solver          smoothSolver;\n"
        "        smoother        GaussSeidel;\n"
        "        tolerance       1e-7;\n"
        "        relTol          0.01;\n"
        "    }\n"
        "}\n\n"
        "SIMPLE\n{\n"
        "    nNonOrthogonalCorrectors 3;\n"
        "    consistent      yes;\n"
        "    pRefCell        0;\n"
        "    pRefValue       0;\n"
        "    residualControl\n    {\n"
        "        p               5e-5;\n"
        "        U               5e-5;\n"
        "        k               5e-5;\n"
        "        omega           5e-5;\n"
        "    }\n"
        "}\n\n"
        "relaxationFactors\n{\n"
        "    fields  { p 0.15; }\n"
        "    equations { U 0.4; k 0.4; omega 0.4; }\n"
        "}\n"
    )

    # ── constant/transportProperties ──
    (case_dir / "constant" / "transportProperties").write_text(
        "FoamFile { version 2.0; format ascii; class dictionary; object transportProperties; }\n"
        "transportModel  Newtonian;\n"
        f"nu              [0 2 -1 0 0 0 0] {nu:.6e};\n"
    )

    # ── constant/turbulenceProperties ──
    (case_dir / "constant" / "turbulenceProperties").write_text(
        "FoamFile { version 2.0; format ascii; class dictionary; object turbulenceProperties; }\n"
        "simulationType RAS;\n"
        "RAS { RASModel kOmegaSST; turbulence on; printCoeffs on; }\n"
    )

    # ── constant/MRFProperties (empty — no rotation for 2D passage) ──
    (case_dir / "constant" / "MRFProperties").write_text(
        "FoamFile { version 2.0; format ascii; class dictionary; object MRFProperties; }\n"
    )

    # ── 0/p (kinematic pressure for simpleFoam) ──
    _write_field(case_dir / "0" / "p",
                 "volScalarField", "p", "[0 2 -2 0 0 0 0]", "uniform 0",
                 inlet="zeroGradient", outlet="fixedValue; value uniform 0",
                 blade="zeroGradient")

    # ── 0/U ──
    U_str = f"({inlet_velocity} 0 0)"
    _write_field(case_dir / "0" / "U",
                 "volVectorField", "U", "[0 1 -1 0 0 0 0]",
                 f"uniform {U_str}",
                 inlet=f"fixedValue; value uniform {U_str}",
                 outlet="inletOutlet; inletValue uniform (0 0 0); value uniform (0 0 0)",
                 blade="noSlip")

    # ── 0/k ──
    _write_field(case_dir / "0" / "k",
                 "volScalarField", "k", "[0 2 -2 0 0 0 0]",
                 f"uniform {k_val:.6e}",
                 inlet=f"fixedValue; value uniform {k_val:.6e}",
                 outlet=f"inletOutlet; inletValue uniform {k_val:.6e}; value uniform {k_val:.6e}",
                 blade=f"kqRWallFunction; value uniform {k_val:.6e}")

    # ── 0/omega ──
    _write_field(case_dir / "0" / "omega",
                 "volScalarField", "omega", "[0 0 -1 0 0 0 0]",
                 f"uniform {omega_val:.6e}",
                 inlet=f"fixedValue; value uniform {omega_val:.6e}",
                 outlet=f"inletOutlet; inletValue uniform {omega_val:.6e}; value uniform {omega_val:.6e}",
                 blade=f"omegaWallFunction; value uniform {omega_val:.6e}")

    # ── 0/nut ──
    _write_field(case_dir / "0" / "nut",
                 "volScalarField", "nut", "[0 2 -1 0 0 0 0]",
                 f"uniform {nut_val:.6e}",
                 inlet=f"calculated; value uniform {nut_val:.6e}",
                 outlet=f"calculated; value uniform {nut_val:.6e}",
                 blade=f"nutkWallFunction; value uniform 0")

    # ── Allrun script ──
    (case_dir / "Allrun").write_text(
        "#!/bin/bash\nset -e\ncd \"${0%/*}\" 2>/dev/null || true\n"
        "blockMesh\nsimpleFoam\n"
    )
    (case_dir / "Allrun").chmod(0o755)

    return case_dir


def _write_field(
    path: Path,
    field_class: str,
    field_name: str,
    dimensions: str,
    internal_field: str,
    inlet: str,
    outlet: str,
    blade: str,
) -> None:
    """Write an OpenFOAM field file with proper cyclic/empty patches."""
    path.write_text(
        f"FoamFile {{ version 2.0; format ascii; class {field_class}; object {field_name}; }}\n"
        f"dimensions      {dimensions};\n"
        f"internalField   {internal_field};\n"
        "boundaryField\n{\n"
        f"    inlet           {{ type {inlet}; }}\n"
        f"    outlet          {{ type {outlet}; }}\n"
        f"    blade           {{ type {blade}; }}\n"
        "    periodic_upper  { type cyclic; }\n"
        "    periodic_lower  { type cyclic; }\n"
        "    frontAndBack    { type empty; }\n"
        "    defaultFaces    { type empty; }\n"
        "}\n"
    )
