"""OpenFOAM blockMeshDict writer.

Ported from V1 writeBlockMeshDictFile.py. Generates the blockMeshDict
file that OpenFOAM's blockMesh utility uses to create structured hex meshes.
"""

from __future__ import annotations

from pathlib import Path
from typing import TextIO

import numpy as np
from numpy.typing import NDArray


@staticmethod
def _format_point(pt: NDArray[np.float64]) -> str:
    """Format a 3D point for blockMeshDict."""
    return f"({pt[0]:.10g} {pt[1]:.10g} {pt[2]:.10g})"


def write_blockmeshdict(
    filepath: str | Path,
    vertices: NDArray[np.float64],
    blocks: list[dict],
    patches: list[dict],
    merge_pairs: list[tuple[str, str]] | None = None,
    convert_to_meters: float = 1.0,
    edges: list[dict] | None = None,
) -> None:
    """Write an OpenFOAM blockMeshDict file.

    Args:
        filepath: Output file path.
        vertices: (N, 3) array of vertex coordinates.
        blocks: List of block definitions, each dict with:
            - 'vertices': list of 8 vertex indices
            - 'cells': [nx, ny, nz] cell counts
            - 'grading': [gx, gy, gz] or 'simpleGrading(1 1 1)'
        patches: List of patch definitions, each dict with:
            - 'name': patch name
            - 'type': 'wall', 'inlet', 'outlet', 'cyclic', 'empty'
            - 'faces': list of [4 vertex indices] per face
        merge_pairs: Optional list of (patch1, patch2) pairs to merge.
        convert_to_meters: Scale factor for unit conversion.
        edges: Optional list of curved edge definitions, each dict with:
            - 'v0': start vertex index
            - 'v1': end vertex index
            - 'points': (N, 3) array of intermediate points
    """
    filepath = Path(filepath)
    filepath.parent.mkdir(parents=True, exist_ok=True)

    with open(filepath, "w") as f:
        _write_header(f)
        f.write(f"scale {convert_to_meters:.6g};\n\n")
        _write_vertices(f, vertices)
        _write_blocks(f, blocks)
        _write_edges(f, edges)
        _write_boundary(f, patches)
        _write_merge_pairs(f, merge_pairs)
        _write_footer(f)


def _write_header(f: TextIO) -> None:
    """Write the FoamFile header."""
    f.write("FoamFile\n{\n")
    f.write("    version     2.0;\n")
    f.write("    format      ascii;\n")
    f.write("    class       dictionary;\n")
    f.write('    object      blockMeshDict;\n')
    f.write("}\n\n")
    f.write("// * * * * * * * * * * * * * * * * * * * * * * * * * * * //\n")
    f.write("// Generated by AstraTurbo\n")
    f.write("// * * * * * * * * * * * * * * * * * * * * * * * * * * * //\n\n")


def _write_vertices(f: TextIO, vertices: NDArray[np.float64]) -> None:
    """Write the vertices section."""
    f.write("vertices\n(\n")
    for i, v in enumerate(vertices):
        f.write(f"    ({float(v[0]):.10g} {float(v[1]):.10g} {float(v[2]):.10g})  // {i}\n")
    f.write(");\n\n")


def _write_blocks(f: TextIO, blocks: list[dict]) -> None:
    """Write the blocks section."""
    f.write("blocks\n(\n")
    for block in blocks:
        verts = " ".join(str(v) for v in block["vertices"])
        cells = " ".join(str(c) for c in block["cells"])
        grading = block.get("grading", [1, 1, 1])
        if isinstance(grading, list):
            g_str = f"simpleGrading ({grading[0]} {grading[1]} {grading[2]})"
        else:
            g_str = str(grading)
        f.write(f"    hex ({verts}) ({cells}) {g_str}\n")
    f.write(");\n\n")


def _write_edges(f: TextIO, edges: list[dict] | None = None) -> None:
    """Write the edges section with optional curved (polyLine) edges.

    Curved edges allow blockMesh to follow blade profiles and other
    non-linear boundaries, rather than linearly interpolating between
    corner vertices.
    """
    f.write("edges\n(\n")
    if edges:
        for edge in edges:
            v0, v1 = edge["v0"], edge["v1"]
            pts = edge["points"]
            f.write(f"    polyLine {v0} {v1}\n    (\n")
            for pt in pts:
                f.write(f"        ({float(pt[0]):.10g} {float(pt[1]):.10g} {float(pt[2]):.10g})\n")
            f.write("    )\n")
    f.write(");\n\n")


def _write_boundary(f: TextIO, patches: list[dict]) -> None:
    """Write the boundary section.

    For cyclic patches in OpenFOAM v2012+, includes the required
    'neighbourPatch' keyword. Cyclic pairs are auto-detected by
    matching *_upper/*_lower or *_0/*_1 naming convention.
    """
    # Build cyclic pair map
    patch_names = [p["name"] for p in patches]
    cyclic_pairs: dict[str, str] = {}
    for name in patch_names:
        if name.endswith("_upper"):
            partner = name.replace("_upper", "_lower")
            if partner in patch_names:
                cyclic_pairs[name] = partner
                cyclic_pairs[partner] = name
        elif name.endswith("_0"):
            partner = name.replace("_0", "_1")
            if partner in patch_names:
                cyclic_pairs[name] = partner
                cyclic_pairs[partner] = name

    f.write("boundary\n(\n")
    for patch in patches:
        f.write(f"    {patch['name']}\n    {{\n")
        f.write(f"        type {patch['type']};\n")
        # Cyclic patches require neighbourPatch in OpenFOAM v2012+
        if patch["type"] == "cyclic" and patch["name"] in cyclic_pairs:
            f.write(f"        neighbourPatch {cyclic_pairs[patch['name']]};\n")
        f.write("        faces\n        (\n")
        for face in patch.get("faces", []):
            face_str = " ".join(str(v) for v in face)
            f.write(f"            ({face_str})\n")
        f.write("        );\n    }\n")
    f.write(");\n\n")


def _write_merge_pairs(
    f: TextIO, merge_pairs: list[tuple[str, str]] | None
) -> None:
    """Write the mergePatchPairs section."""
    f.write("mergePatchPairs\n(\n")
    if merge_pairs:
        for p1, p2 in merge_pairs:
            f.write(f"    ({p1} {p2})\n")
    f.write(");\n\n")


def _write_footer(f: TextIO) -> None:
    """Write the closing comment."""
    f.write("// ************************************************************************* //\n")
