"""HTML report generator for turbomachinery design results.

Produces a self-contained HTML file with:
  - Design summary (requirements, overall performance)
  - Per-stage velocity triangles and blade parameters
  - Compressor map (if off-design was run)
  - Material properties (including temperature-dependent)
  - Mesh quality summary (if mesh was generated)
"""

from __future__ import annotations

import html
import math
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path


@dataclass
class ReportConfig:
    """Configuration for report generation."""

    title: str = "AstraTurbo Design Report"
    author: str = ""
    project: str = ""
    output_path: str = "report.html"
    include_map: bool = True
    include_materials: bool = True


def _css() -> str:
    return """
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
               max-width: 900px; margin: 40px auto; padding: 0 20px; color: #333; line-height: 1.6; }
        h1 { color: #1a5276; border-bottom: 3px solid #1a5276; padding-bottom: 10px; }
        h2 { color: #2c3e50; border-bottom: 1px solid #ddd; padding-bottom: 5px; margin-top: 30px; }
        h3 { color: #34495e; }
        table { border-collapse: collapse; width: 100%; margin: 15px 0; }
        th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: right; }
        th { background-color: #2c3e50; color: white; text-align: center; }
        tr:nth-child(even) { background-color: #f8f9fa; }
        tr:hover { background-color: #e8f4f8; }
        .summary-box { background: #eaf2f8; border-left: 4px solid #2980b9;
                       padding: 15px; margin: 15px 0; border-radius: 4px; }
        .warning { background: #fdebd0; border-left: 4px solid #e67e22; }
        .danger { background: #fadbd8; border-left: 4px solid #e74c3c; }
        .good { background: #d5f5e3; border-left: 4px solid #27ae60; }
        .meta { color: #7f8c8d; font-size: 0.9em; }
        pre { background: #f4f6f7; padding: 12px; border-radius: 4px;
              overflow-x: auto; font-size: 0.9em; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd;
                  color: #95a5a6; font-size: 0.85em; text-align: center; }
    </style>
    """


def _header(config: ReportConfig) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        "<!DOCTYPE html><html><head>",
        f"<title>{html.escape(config.title)}</title>",
        "<meta charset='utf-8'>",
        _css(),
        "</head><body>",
        f"<h1>{html.escape(config.title)}</h1>",
        "<p class='meta'>",
    ]
    if config.author:
        lines.append(f"Author: {html.escape(config.author)}<br>")
    if config.project:
        lines.append(f"Project: {html.escape(config.project)}<br>")
    lines.append(f"Generated: {now} by AstraTurbo</p>")
    return "\n".join(lines)


def _footer() -> str:
    return (
        "<div class='footer'>"
        "Generated by AstraTurbo &mdash; Open-source turbomachinery design platform"
        "</div></body></html>"
    )


def _meanline_section(result) -> str:
    """Generate meanline design summary section."""
    lines = ["<h2>Meanline Design Summary</h2>"]

    # Overall performance box
    lines.append("<div class='summary-box'>")
    lines.append(f"<strong>Stages:</strong> {result.n_stages} &nbsp;&nbsp;")
    lines.append(f"<strong>Overall PR:</strong> {result.overall_pressure_ratio:.4f} &nbsp;&nbsp;")
    lines.append(f"<strong>Overall TR:</strong> {result.overall_temperature_ratio:.4f} &nbsp;&nbsp;")
    lines.append(f"<strong>Efficiency:</strong> {result.overall_efficiency:.4f} &nbsp;&nbsp;")
    lines.append(f"<strong>Total Work:</strong> {result.total_work:.0f} J/kg")
    lines.append("</div>")

    # Per-stage table
    lines.append("<h3>Stage-by-Stage Performance</h3>")
    lines.append("<table>")
    lines.append(
        "<tr><th>Stage</th><th>PR</th><th>&eta;</th>"
        "<th>&phi;</th><th>&psi;</th><th>R</th>"
        "<th>De Haller</th><th>Status</th></tr>"
    )
    for s in result.stages:
        dh = s.rotor_triangles.de_haller_ratio
        dh_class = "good" if dh > 0.72 else "danger"
        lines.append(
            f"<tr><td>{s.stage_number}</td>"
            f"<td>{s.pressure_ratio:.4f}</td>"
            f"<td>{s.isentropic_efficiency:.4f}</td>"
            f"<td>{s.flow_coefficient:.3f}</td>"
            f"<td>{s.loading_coefficient:.3f}</td>"
            f"<td>{s.degree_of_reaction:.3f}</td>"
            f"<td class='{dh_class}'>{dh:.3f}</td>"
            f"<td>{'OK' if dh > 0.72 else 'De Haller &lt; 0.72'}</td></tr>"
        )
    lines.append("</table>")

    # Blade angles table
    lines.append("<h3>Blade Angles</h3>")
    lines.append("<table>")
    lines.append(
        "<tr><th>Stage</th><th>&beta;<sub>in</sub> (&deg;)</th>"
        "<th>&beta;<sub>out</sub> (&deg;)</th>"
        "<th>&alpha;<sub>in</sub> (&deg;)</th>"
        "<th>&alpha;<sub>out</sub> (&deg;)</th></tr>"
    )
    for s in result.stages:
        a = s.blade_angles_deg()
        lines.append(
            f"<tr><td>{s.stage_number}</td>"
            f"<td>{a['rotor_inlet_beta']:.1f}</td>"
            f"<td>{a['rotor_outlet_beta']:.1f}</td>"
            f"<td>{a['stator_inlet_alpha']:.1f}</td>"
            f"<td>{a['stator_outlet_alpha']:.1f}</td></tr>"
        )
    lines.append("</table>")

    return "\n".join(lines)


def _off_design_section(od_result) -> str:
    """Generate off-design analysis section."""
    lines = ["<h2>Off-Design Analysis</h2>"]

    status_class = "danger" if od_result.is_stalled else "good"
    lines.append(f"<div class='summary-box {status_class}'>")
    lines.append(f"<strong>Overall PR:</strong> {od_result.overall_pr:.4f} &nbsp;&nbsp;")
    lines.append(f"<strong>Efficiency:</strong> {od_result.overall_efficiency:.4f} &nbsp;&nbsp;")
    lines.append(f"<strong>Stalled:</strong> {od_result.is_stalled} &nbsp;&nbsp;")
    lines.append(f"<strong>Choked:</strong> {od_result.is_choked}")
    lines.append("</div>")

    lines.append("<table>")
    lines.append(
        "<tr><th>Stage</th><th>PR</th><th>&eta;</th><th>DF</th>"
        "<th>Incidence (&deg;)</th><th>Loss</th><th>Status</th></tr>"
    )
    for s in od_result.stages:
        stall_class = "danger" if s["is_stalled"] else ""
        lines.append(
            f"<tr class='{stall_class}'><td>{s['stage']}</td>"
            f"<td>{s['PR']:.4f}</td>"
            f"<td>{s['efficiency']:.4f}</td>"
            f"<td>{s['DF']:.4f}</td>"
            f"<td>{s['incidence_deg']:.2f}</td>"
            f"<td>{s['loss_total']:.5f}</td>"
            f"<td>{'STALL' if s['is_stalled'] else 'OK'}</td></tr>"
        )
    lines.append("</table>")
    return "\n".join(lines)


def _compressor_map_section(cmap) -> str:
    """Generate compressor map section."""
    lines = ["<h2>Compressor Map</h2>"]

    if cmap.design_point:
        dp = cmap.design_point
        lines.append("<div class='summary-box'>")
        lines.append(f"<strong>Design Point:</strong> "
                     f"m&#775;={dp.get('mass_flow', 0):.2f} kg/s, "
                     f"PR={dp.get('pr', 0):.4f}, "
                     f"&eta;={dp.get('efficiency', 0):.4f}, "
                     f"RPM={dp.get('rpm', 0):.0f}")
        lines.append("</div>")

    for sl in cmap.speed_lines:
        lines.append(f"<h3>N/N<sub>des</sub> = {sl.rpm_fraction:.2f}</h3>")
        lines.append("<table>")
        lines.append(
            "<tr><th>m&#775; (kg/s)</th><th>PR</th><th>&eta;</th>"
            "<th>Stalled</th><th>Choked</th></tr>"
        )
        for j in range(len(sl.mass_flows)):
            row_class = "danger" if sl.is_stalled[j] else ""
            lines.append(
                f"<tr class='{row_class}'>"
                f"<td>{sl.mass_flows[j]:.3f}</td>"
                f"<td>{sl.pressure_ratios[j]:.4f}</td>"
                f"<td>{sl.efficiencies[j]:.4f}</td>"
                f"<td>{'YES' if sl.is_stalled[j] else '-'}</td>"
                f"<td>{'YES' if sl.is_choked[j] else '-'}</td></tr>"
            )
        lines.append("</table>")
        if sl.surge_point_index is not None:
            idx = sl.surge_point_index
            lines.append(
                f"<p><em>Surge point: m&#775;={sl.mass_flows[idx]:.3f} kg/s, "
                f"PR={sl.pressure_ratios[idx]:.4f}</em></p>"
            )

    if cmap.surge_line:
        lines.append("<h3>Surge Line</h3><table>")
        lines.append("<tr><th>m&#775; (kg/s)</th><th>PR</th></tr>")
        for mf, pr in cmap.surge_line:
            lines.append(f"<tr><td>{mf:.3f}</td><td>{pr:.4f}</td></tr>")
        lines.append("</table>")

    return "\n".join(lines)


def _material_section(material, temperature: float | None = None) -> str:
    """Generate material properties section."""
    lines = ["<h2>Material Properties</h2>"]
    lines.append(f"<h3>{html.escape(material.name)}</h3>")
    lines.append("<table>")
    lines.append("<tr><th>Property</th><th>Room Temp (293 K)</th>")
    if temperature and material.youngs_modulus_table:
        lines.append(f"<th>At {temperature:.0f} K</th><th>Ratio</th>")
    lines.append("</tr>")

    E_room = material.youngs_modulus
    Sy_room = material.yield_strength
    k_room = material.thermal_conductivity

    rows = [
        ("Young's Modulus", f"{E_room/1e9:.1f} GPa"),
        ("Yield Strength", f"{Sy_room/1e6:.0f} MPa"),
        ("Thermal Conductivity", f"{k_room:.1f} W/m-K"),
        ("Density", f"{material.density:.0f} kg/m&sup3;"),
        ("Max Service Temp", f"{material.max_service_temperature:.0f} K"),
    ]

    if temperature and material.youngs_modulus_table:
        E_hot = material.youngs_modulus_at(temperature)
        Sy_hot = material.yield_strength_at(temperature)
        k_hot = material.thermal_conductivity_at(temperature)
        hot_cols = [
            (f"{E_hot/1e9:.1f} GPa", f"{E_hot/E_room:.0%}"),
            (f"{Sy_hot/1e6:.0f} MPa", f"{Sy_hot/Sy_room:.0%}"),
            (f"{k_hot:.1f} W/m-K", f"{k_hot/k_room:.0%}"),
            ("-", "-"),
            ("-", "-"),
        ]
    else:
        hot_cols = None

    for i, (name, room_val) in enumerate(rows):
        lines.append(f"<tr><td style='text-align:left'>{name}</td><td>{room_val}</td>")
        if hot_cols:
            lines.append(f"<td>{hot_cols[i][0]}</td><td>{hot_cols[i][1]}</td>")
        lines.append("</tr>")

    lines.append("</table>")

    if temperature and material.youngs_modulus_table:
        Sy_hot = material.yield_strength_at(temperature)
        if Sy_hot < Sy_room * 0.5:
            lines.append(
                f"<div class='summary-box warning'>"
                f"Yield strength at {temperature:.0f} K is {Sy_hot/Sy_room:.0%} of room temp. "
                f"Safety factors must account for temperature derating.</div>"
            )

    return "\n".join(lines)


def _turbine_section(result) -> str:
    """Generate turbine design summary section."""
    lines = ["<h2>Turbine Meanline Design</h2>"]

    lines.append("<div class='summary-box'>")
    lines.append(f"<strong>Stages:</strong> {result.n_stages} &nbsp;&nbsp;")
    lines.append(f"<strong>Overall ER:</strong> {result.overall_expansion_ratio:.4f} &nbsp;&nbsp;")
    lines.append(f"<strong>Overall TR:</strong> {result.overall_temperature_ratio:.4f} &nbsp;&nbsp;")
    lines.append(f"<strong>Efficiency:</strong> {result.overall_efficiency:.4f} &nbsp;&nbsp;")
    lines.append(f"<strong>Total Work:</strong> {result.total_work:.0f} J/kg")
    lines.append("</div>")

    # Per-stage table
    lines.append("<h3>Stage-by-Stage Performance</h3>")
    lines.append("<table>")
    lines.append(
        "<tr><th>Stage</th><th>ER</th><th>&eta;</th>"
        "<th>&phi;</th><th>&psi;</th><th>R</th>"
        "<th>Zweifel</th><th>Nozzle M</th></tr>"
    )
    for s in result.stages:
        z_class = "good" if 0.6 <= s.zweifel_coefficient <= 1.2 else "warning"
        lines.append(
            f"<tr><td>{s.stage_number}</td>"
            f"<td>{s.expansion_ratio:.4f}</td>"
            f"<td>{s.isentropic_efficiency:.4f}</td>"
            f"<td>{s.flow_coefficient:.3f}</td>"
            f"<td>{s.loading_coefficient:.3f}</td>"
            f"<td>{s.degree_of_reaction:.3f}</td>"
            f"<td class='{z_class}'>{s.zweifel_coefficient:.3f}</td>"
            f"<td>{s.nozzle_exit_mach:.3f}</td></tr>"
        )
    lines.append("</table>")

    # Blade angles table
    lines.append("<h3>Blade Angles</h3>")
    lines.append("<table>")
    lines.append(
        "<tr><th>Stage</th>"
        "<th>NGV &alpha;<sub>in</sub> (&deg;)</th>"
        "<th>NGV &alpha;<sub>out</sub> (&deg;)</th>"
        "<th>Rotor &beta;<sub>in</sub> (&deg;)</th>"
        "<th>Rotor &beta;<sub>out</sub> (&deg;)</th></tr>"
    )
    for s in result.stages:
        a = s.blade_angles_deg()
        lines.append(
            f"<tr><td>{s.stage_number}</td>"
            f"<td>{a['nozzle_inlet_alpha']:.1f}</td>"
            f"<td>{a['nozzle_outlet_alpha']:.1f}</td>"
            f"<td>{a['rotor_inlet_beta']:.1f}</td>"
            f"<td>{a['rotor_outlet_beta']:.1f}</td></tr>"
        )
    lines.append("</table>")

    return "\n".join(lines)


def _centrifugal_section(result) -> str:
    """Generate centrifugal compressor section."""
    lines = ["<h2>Centrifugal Compressor Design</h2>"]
    lines.append("<div class='summary-box'>")
    lines.append(f"<strong>Type:</strong> Centrifugal &nbsp;&nbsp;")
    lines.append(f"<strong>PR:</strong> {result.pressure_ratio:.4f} &nbsp;&nbsp;")
    lines.append(f"<strong>Efficiency:</strong> {result.isentropic_efficiency:.4f} &nbsp;&nbsp;")
    lines.append(f"<strong>Power:</strong> {result.power_kW:.1f} kW &nbsp;&nbsp;")
    lines.append(f"<strong>Tip Speed:</strong> {result.tip_speed:.0f} m/s")
    lines.append("</div>")

    lines.append("<h3>Impeller</h3><table>")
    imp = result.impeller
    lines.append("<tr><th>Parameter</th><th>Value</th></tr>")
    for k, v in [
        ("Inlet tip radius", f"{imp['r1_tip']:.4f} m"),
        ("Outlet radius", f"{imp['r2']:.4f} m"),
        ("Backsweep angle", f"{imp['beta2_blade_deg']:.1f}&deg;"),
        ("Slip factor", f"{imp['slip_factor']:.4f}"),
        ("Number of blades", f"{imp['n_blades']}"),
        ("Inlet relative Mach", f"{imp['M_w1']:.3f}"),
        ("Tip speed", f"{imp['U2']:.0f} m/s"),
    ]:
        lines.append(f"<tr><td style='text-align:left'>{k}</td><td>{v}</td></tr>")
    lines.append("</table>")

    lines.append("<h3>Diffuser</h3><table>")
    diff = result.diffuser
    lines.append("<tr><th>Parameter</th><th>Value</th></tr>")
    for k, v in [
        ("Inlet radius", f"{diff['r3']:.4f} m"),
        ("Outlet radius", f"{diff['r4']:.4f} m"),
        ("Type", diff.get("type", "vaneless")),
        ("Pressure recovery", f"{diff['Cp']:.4f}"),
    ]:
        lines.append(f"<tr><td style='text-align:left'>{k}</td><td>{v}</td></tr>")
    lines.append("</table>")

    return "\n".join(lines)


def generate_report(
    config: ReportConfig | None = None,
    meanline_result=None,
    off_design_result=None,
    compressor_map=None,
    centrifugal_result=None,
    turbine_result=None,
    material=None,
    material_temperature: float | None = None,
    blade_params: list[dict] | None = None,
) -> str:
    """Generate an HTML design report.

    Args:
        config: Report configuration.
        meanline_result: MeanlineResult from design-point solver.
        off_design_result: OffDesignResult from off-design analysis.
        compressor_map: CompressorMap from map generation.
        centrifugal_result: CentrifugalResult from centrifugal solver.
        material: Material object for properties section.
        material_temperature: Operating temperature for temp-dependent display.
        blade_params: Blade parameters from meanline_to_blade_parameters().

    Returns:
        Path to the generated HTML file.
    """
    if config is None:
        config = ReportConfig()

    parts = [_header(config)]

    if meanline_result is not None:
        parts.append(_meanline_section(meanline_result))

    if off_design_result is not None:
        parts.append(_off_design_section(off_design_result))

    if compressor_map is not None and config.include_map:
        parts.append(_compressor_map_section(compressor_map))

    if centrifugal_result is not None:
        parts.append(_centrifugal_section(centrifugal_result))

    if turbine_result is not None:
        parts.append(_turbine_section(turbine_result))

    if material is not None and config.include_materials:
        parts.append(_material_section(material, material_temperature))

    if blade_params:
        parts.append("<h2>Blade Parameters</h2>")
        parts.append("<table>")
        parts.append(
            "<tr><th>Stage</th><th>Rotor Stagger (&deg;)</th>"
            "<th>Rotor Camber (&deg;)</th><th>Solidity</th>"
            "<th>Stator Stagger (&deg;)</th><th>Stator Camber (&deg;)</th></tr>"
        )
        for p in blade_params:
            parts.append(
                f"<tr><td>{p['stage']}</td>"
                f"<td>{p['rotor_stagger_deg']:.1f}</td>"
                f"<td>{p['rotor_camber_deg']:.1f}</td>"
                f"<td>{p['rotor_solidity']:.2f}</td>"
                f"<td>{p['stator_stagger_deg']:.1f}</td>"
                f"<td>{p['stator_camber_deg']:.1f}</td></tr>"
            )
        parts.append("</table>")

    parts.append(_footer())

    html_content = "\n".join(parts)
    output = Path(config.output_path)
    output.write_text(html_content, encoding="utf-8")
    return str(output)
