"""Validation test: mesh quality bounds.

Generates meshes using AstraTurbo's mesh generators and verifies
that quality metrics are within acceptable bounds:
  - Aspect ratio < 100
  - Skewness < 0.9
  - Point count matches expected (Ni * Nj)
  - Cell count matches expected (Ni-1) * (Nj-1)
"""

from __future__ import annotations

import numpy as np
import pytest


class TestMeshQualityBounds:
    """Verify mesh quality metrics are within acceptable bounds."""

    def _generate_simple_mesh(
        self,
        ni: int = 20,
        nj: int = 15,
        distortion: float = 0.0,
    ) -> np.ndarray:
        """Generate a simple test mesh with optional distortion.

        Creates a structured mesh on [0,1] x [0,1] with optional
        random perturbation of interior points.

        Args:
            ni: Points in i-direction.
            nj: Points in j-direction.
            distortion: Max random displacement as fraction of cell size.

        Returns:
            (ni, nj, 2) mesh array.
        """
        x = np.linspace(0, 1, ni)
        y = np.linspace(0, 1, nj)
        xx, yy = np.meshgrid(x, y, indexing="ij")

        mesh = np.zeros((ni, nj, 2), dtype=np.float64)
        mesh[:, :, 0] = xx
        mesh[:, :, 1] = yy

        if distortion > 0:
            rng = np.random.default_rng(42)
            dx = 1.0 / (ni - 1)
            dy = 1.0 / (nj - 1)
            noise_x = rng.uniform(-distortion * dx, distortion * dx, (ni, nj))
            noise_y = rng.uniform(-distortion * dy, distortion * dy, (ni, nj))
            # Only distort interior
            noise_x[0, :] = 0
            noise_x[-1, :] = 0
            noise_x[:, 0] = 0
            noise_x[:, -1] = 0
            noise_y[0, :] = 0
            noise_y[-1, :] = 0
            noise_y[:, 0] = 0
            noise_y[:, -1] = 0
            mesh[:, :, 0] += noise_x
            mesh[:, :, 1] += noise_y

        return mesh

    def test_uniform_mesh_aspect_ratio(self) -> None:
        """Uniform square mesh should have aspect ratio close to 1."""
        from astraturbo.mesh.quality import compute_aspect_ratio

        mesh = self._generate_simple_mesh(ni=20, nj=20, distortion=0.0)
        aspect = compute_aspect_ratio(mesh)

        assert np.max(aspect) < 100.0, (
            f"Max aspect ratio {np.max(aspect)} exceeds limit"
        )
        assert np.max(aspect) < 1.5, (
            "Uniform square mesh should have aspect ratio near 1"
        )

    def test_uniform_mesh_skewness(self) -> None:
        """Uniform rectangular mesh should have near-zero skewness."""
        from astraturbo.mesh.quality import compute_skewness

        mesh = self._generate_simple_mesh(ni=20, nj=20, distortion=0.0)
        skew = compute_skewness(mesh)

        assert np.max(skew) < 0.9, (
            f"Max skewness {np.max(skew)} exceeds limit"
        )
        assert np.max(skew) < 0.1, (
            "Uniform mesh should have near-zero skewness"
        )

    def test_distorted_mesh_within_bounds(self) -> None:
        """Moderately distorted mesh should still pass quality bounds."""
        from astraturbo.mesh.quality import compute_aspect_ratio, compute_skewness

        mesh = self._generate_simple_mesh(ni=30, nj=25, distortion=0.2)
        aspect = compute_aspect_ratio(mesh)
        skew = compute_skewness(mesh)

        assert np.max(aspect) < 100.0, (
            f"Max aspect ratio {np.max(aspect)} exceeds 100"
        )
        assert np.max(skew) < 0.9, (
            f"Max skewness {np.max(skew)} exceeds 0.9"
        )

    def test_cell_count_matches_expected(self) -> None:
        """Number of cells should be (Ni-1) * (Nj-1)."""
        from astraturbo.mesh.quality import mesh_quality_report

        ni, nj = 25, 18
        mesh = self._generate_simple_mesh(ni=ni, nj=nj)
        report = mesh_quality_report(mesh)

        expected_cells = (ni - 1) * (nj - 1)
        assert report["n_cells"] == expected_cells, (
            f"Expected {expected_cells} cells, got {report['n_cells']}"
        )

    def test_point_count_matches_expected(self) -> None:
        """Number of points should be Ni * Nj."""
        from astraturbo.mesh.quality import mesh_quality_report

        ni, nj = 25, 18
        mesh = self._generate_simple_mesh(ni=ni, nj=nj)
        report = mesh_quality_report(mesh)

        expected_points = ni * nj
        assert report["n_points"] == expected_points, (
            f"Expected {expected_points} points, got {report['n_points']}"
        )

    def test_tfi_mesh_quality(self) -> None:
        """Test quality of a mesh generated by transfinite interpolation."""
        from astraturbo.mesh.transfinite import tfi_2d
        from astraturbo.mesh.quality import compute_aspect_ratio, compute_skewness

        ni, nj = 20, 15

        # Curved boundaries
        t_s = np.linspace(0, 1, ni)
        t_t = np.linspace(0, 1, nj)

        bottom = np.column_stack([t_s, 0.1 * np.sin(np.pi * t_s)])
        top = np.column_stack([t_s, 1.0 + 0.05 * np.sin(np.pi * t_s)])
        left = np.column_stack([np.zeros(nj), t_t])
        right = np.column_stack([np.ones(nj), t_t])

        # Fix corners
        left[0] = bottom[0]
        left[-1] = top[0]
        right[0] = bottom[-1]
        right[-1] = top[-1]

        mesh = tfi_2d(bottom, top, left, right)
        aspect = compute_aspect_ratio(mesh)
        skew = compute_skewness(mesh)

        assert np.max(aspect) < 100.0, (
            f"TFI mesh aspect ratio {np.max(aspect)} > 100"
        )
        assert np.max(skew) < 0.9, (
            f"TFI mesh skewness {np.max(skew)} > 0.9"
        )
        assert mesh.shape == (ni, nj, 2), (
            f"Expected shape ({ni}, {nj}, 2), got {mesh.shape}"
        )

    def test_stretched_mesh_aspect_ratio(self) -> None:
        """A highly stretched mesh should have high AR but still < 100."""
        from astraturbo.mesh.quality import compute_aspect_ratio

        ni, nj = 20, 10
        x = np.linspace(0, 1, ni)
        y = np.linspace(0, 0.05, nj)  # Very thin domain
        xx, yy = np.meshgrid(x, y, indexing="ij")

        mesh = np.zeros((ni, nj, 2), dtype=np.float64)
        mesh[:, :, 0] = xx
        mesh[:, :, 1] = yy

        aspect = compute_aspect_ratio(mesh)

        # For this mesh: dx ~ 1/19 ~ 0.053, dy ~ 0.05/9 ~ 0.0056
        # AR ~ 0.053/0.0056 ~ 9.5
        assert np.max(aspect) < 100.0
        assert np.max(aspect) > 5.0, "Should have noticeable stretch"

    def test_quality_report_keys(self) -> None:
        """mesh_quality_report should return all expected keys."""
        from astraturbo.mesh.quality import mesh_quality_report

        mesh = self._generate_simple_mesh()
        report = mesh_quality_report(mesh)

        required_keys = [
            "aspect_ratio_max",
            "aspect_ratio_mean",
            "skewness_max",
            "skewness_mean",
            "n_cells",
            "n_points",
        ]
        for key in required_keys:
            assert key in report, f"Missing key '{key}' in quality report"

    def test_auto_first_cell_height(self) -> None:
        """Test auto_first_cell_height returns reasonable values."""
        from astraturbo.mesh.quality import auto_first_cell_height

        result = auto_first_cell_height(
            velocity=150.0,
            chord=0.05,
            density=1.225,
            dynamic_viscosity=1.8e-5,
            target_yplus=1.0,
        )

        # First cell height should be very small (microns range)
        assert result["first_cell_height"] > 0
        assert result["first_cell_height"] < 0.001  # Less than 1 mm

        # Grading ratio should be > 1
        assert result["grading_ratio"] > 1.0
        assert result["grading_ratio"] < 5.0

        # Reynolds number should be reasonable
        Re_expected = 1.225 * 150.0 * 0.05 / 1.8e-5
        assert result["reynolds_number"] == pytest.approx(Re_expected, rel=1e-6)

        # BL thickness should be reasonable
        assert result["boundary_layer_thickness"] > 0
        assert result["boundary_layer_thickness"] < 0.05  # Less than chord
