"""Multi-block structured mesh generator.

Native Python replacement for GridZ scripting. Generates structured
multi-block CGNS meshes from polyline-defined block boundaries.

This fills the adaptation requirement:
  "Use this data, script it using GridZ to generate a multi-block
   structured CGNS mesh"

Instead of scripting GridZ externally, this module performs the same
function natively: takes polyline boundaries for each block, applies
grading, generates structured interior points via TFI, and exports
to CGNS.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
from numpy.typing import NDArray

from .polyline import Polyline, BlockEdge
from .grading import (
    compute_graded_parameters,
    project_grading_onto_polyline,
    compute_boundary_layer_grading,
)
from .transfinite import tfi_2d_vectorized
from .vertex_extraction import BlockTopology, BlockVertex


@dataclass
class StructuredBlock:
    """A single block of a multi-block structured mesh.

    Contains the computed grid points and metadata.
    """

    name: str
    points: NDArray[np.float64]  # (Ni, Nj, D) grid coordinates
    n_cells_i: int = 0
    n_cells_j: int = 0
    grading_i: float = 1.0
    grading_j: float = 1.0

    # Boundary patches on this block
    patches: dict[str, str] = field(default_factory=dict)
    # e.g. {"bottom": "blade", "top": "passage", "left": "inlet", "right": "outlet"}


@dataclass
class MultiBlockMesh:
    """Complete multi-block structured mesh.

    Contains all blocks and their connectivity, ready for CGNS export.
    """

    blocks: list[StructuredBlock] = field(default_factory=list)
    name: str = "AstraTurbo_Mesh"
    o10h_data: dict | None = field(default=None, repr=False)

    @property
    def n_blocks(self) -> int:
        return len(self.blocks)

    @property
    def total_cells(self) -> int:
        total = 0
        for b in self.blocks:
            ni, nj = b.points.shape[0] - 1, b.points.shape[1] - 1
            total += ni * nj
        return total

    @property
    def total_points(self) -> int:
        return sum(b.points.shape[0] * b.points.shape[1] for b in self.blocks)

    def get_block(self, name: str) -> StructuredBlock | None:
        for b in self.blocks:
            if b.name == name:
                return b
        return None

    def export_cgns(self, filepath: str | Path) -> None:
        """Export the multi-block mesh to CGNS format."""
        from ..export.cgns_writer import write_cgns_structured

        block_arrays = [b.points for b in self.blocks]
        block_names = [b.name for b in self.blocks]
        write_cgns_structured(filepath, block_arrays, block_names, self.name)

    def export_openfoam(self, filepath: str | Path, z_thickness: float = 0.001) -> None:
        """Export to OpenFOAM blockMeshDict format.

        Generates a valid blockMeshDict with correct hex vertex ordering
        (right-hand rule) for OpenFOAM's blockMesh utility.

        For O10H topology meshes (generated by generate_blade_passage_mesh),
        uses direct vertex/block/patch generation from the stored O10H data
        for correct multi-block connectivity and polyLine curved edges.

        For generic meshes, extrudes 2D blocks to 3D and detects curved edges
        from the full grid point data.

        Args:
            filepath: Output path for blockMeshDict.
            z_thickness: Thickness of the 2D slab extrusion (m). Default 0.001.
                For blade passage meshes, use ~1% of pitch.
        """
        from ..export.openfoam_writer import write_blockmeshdict

        # ── O10H direct export path ──
        if self.o10h_data is not None:
            self._export_openfoam_o10h(filepath, z_thickness)
            return

        # ── Generic per-block export path ──
        all_vertices = []
        all_blocks_def = []
        all_edges = []  # polyLine curved edges
        vertex_offset = 0

        # Collect patch faces: {name: {"type": ..., "faces": [...]}}
        patch_map: dict[str, dict] = {}
        _of_type = {
            "blade": "wall", "inlet": "patch", "outlet": "patch",
            "periodic_upper": "cyclic", "periodic_lower": "cyclic",
            "hub": "wall", "shroud": "wall",
        }

        for block in self.blocks:
            ni, nj = block.points.shape[0], block.points.shape[1]
            dim = block.points.shape[2]

            corners_2d = [
                block.points[0, 0],
                block.points[-1, 0],
                block.points[-1, -1],
                block.points[0, -1],
            ]

            if dim == 2:
                # Check winding: positive cross_z = CCW (correct)
                edge01 = corners_2d[1] - corners_2d[0]
                edge03 = corners_2d[3] - corners_2d[0]
                cross_z = edge01[0] * edge03[1] - edge01[1] * edge03[0]
                flipped = cross_z < 0
                if flipped:
                    corners_2d = [corners_2d[0], corners_2d[3],
                                  corners_2d[2], corners_2d[1]]

                for c in corners_2d:
                    all_vertices.append(np.array([c[0], c[1], 0.0]))
                for c in corners_2d:
                    all_vertices.append(np.array([c[0], c[1], z_thickness]))

                v = vertex_offset
                all_blocks_def.append({
                    "vertices": [v, v+1, v+2, v+3, v+4, v+5, v+6, v+7],
                    "cells": [ni - 1, nj - 1, 1],
                    "grading": [1, 1, 1],
                })

                # Extract curved edges from the full grid data.
                # Block edges in the hex:
                #   bottom-face edges (z=0): v0→v1 (i-dir, j=0), v3→v2 (i-dir, j=max),
                #                            v0→v3 (j-dir, i=0), v1→v2 (j-dir, i=max)
                #   top-face edges (z=z_t): same pattern offset by +4
                # We define polyLines for edges where the intermediate points
                # deviate significantly from a straight line.
                edge_curves_2d = {
                    # (start_vertex_local, end_vertex_local): points array
                }
                if not flipped:
                    # Normal winding: 0=(0,0), 1=(max,0), 2=(max,max), 3=(0,max)
                    edge_curves_2d[(0, 1)] = block.points[:, 0, :]     # i-dir, j=0 (bottom)
                    edge_curves_2d[(3, 2)] = block.points[:, -1, :]    # i-dir, j=max (top)
                    edge_curves_2d[(0, 3)] = block.points[0, :, :]     # j-dir, i=0 (left)
                    edge_curves_2d[(1, 2)] = block.points[-1, :, :]    # j-dir, i=max (right)
                else:
                    # Flipped winding: 0=(0,0), 1=(0,max), 2=(max,max), 3=(max,0)
                    edge_curves_2d[(0, 1)] = block.points[0, :, :]     # j-dir, i=0
                    edge_curves_2d[(3, 2)] = block.points[-1, :, :]    # j-dir, i=max
                    edge_curves_2d[(0, 3)] = block.points[:, 0, :]     # i-dir, j=0
                    edge_curves_2d[(1, 2)] = block.points[:, -1, :]    # i-dir, j=max

                for (lv0, lv1), pts_2d in edge_curves_2d.items():
                    if len(pts_2d) < 3:
                        continue
                    # Check if edge is significantly curved (max deviation from line)
                    p0 = pts_2d[0]
                    p1 = pts_2d[-1]
                    line_dir = p1 - p0
                    line_len = np.linalg.norm(line_dir)
                    if line_len < 1e-15:
                        continue
                    line_dir /= line_len
                    # Perpendicular distance of each intermediate point from the line
                    deviations = np.abs(
                        (pts_2d[1:-1, 0] - p0[0]) * (-line_dir[1]) +
                        (pts_2d[1:-1, 1] - p0[1]) * line_dir[0]
                    )
                    max_dev = np.max(deviations) if len(deviations) > 0 else 0.0

                    # Only add polyLine if deviation > 0.1% of edge length
                    if max_dev > 0.001 * line_len:
                        # Subsample to ~20 intermediate points for efficiency
                        n_pts = len(pts_2d)
                        if n_pts > 22:
                            indices = np.linspace(1, n_pts - 2, 20, dtype=int)
                            intermediate = pts_2d[indices]
                        else:
                            intermediate = pts_2d[1:-1]

                        gv0 = v + lv0  # global vertex index (z=0 layer)
                        gv1 = v + lv1
                        pts_3d_z0 = np.column_stack([
                            intermediate[:, 0], intermediate[:, 1],
                            np.zeros(len(intermediate))
                        ])
                        pts_3d_zt = np.column_stack([
                            intermediate[:, 0], intermediate[:, 1],
                            np.full(len(intermediate), z_thickness)
                        ])
                        all_edges.append({
                            "v0": gv0, "v1": gv1,
                            "points": pts_3d_z0,
                        })
                        all_edges.append({
                            "v0": gv0 + 4, "v1": gv1 + 4,
                            "points": pts_3d_zt,
                        })

                # Face definitions for this hex
                face_defs = {
                    "bottom": [v, v+1, v+5, v+4],
                    "top":    [v+3, v+7, v+6, v+2],
                    "left":   [v, v+4, v+7, v+3],
                    "right":  [v+1, v+2, v+6, v+5],
                }

                # z-faces → frontAndBack (empty for 2D)
                if "frontAndBack" not in patch_map:
                    patch_map["frontAndBack"] = {"type": "empty", "faces": []}
                patch_map["frontAndBack"]["faces"].append([v+4, v+5, v+6, v+7])
                patch_map["frontAndBack"]["faces"].append([v, v+3, v+2, v+1])

                # Map block.patches to named boundary faces
                for face_name, boundary_name in block.patches.items():
                    if face_name in face_defs:
                        of_type = _of_type.get(boundary_name, "patch")
                        if boundary_name not in patch_map:
                            patch_map[boundary_name] = {"type": of_type, "faces": []}
                        patch_map[boundary_name]["faces"].append(face_defs[face_name])

                vertex_offset += 8
            elif len(block.points.shape) == 4:
                # True 3D block: shape (ni, nj, nk, 3)
                ni, nj, nk = block.points.shape[:3]
                # 8 corners: bottom face (k=0), top face (k=-1)
                c = [
                    block.points[0,    0,    0],     # 0: bottom
                    block.points[-1,   0,    0],     # 1
                    block.points[-1,  -1,    0],     # 2
                    block.points[0,   -1,    0],     # 3
                    block.points[0,    0,   -1],     # 4: top
                    block.points[-1,   0,   -1],     # 5
                    block.points[-1,  -1,   -1],     # 6
                    block.points[0,   -1,   -1],     # 7
                ]
                # Check winding: bottom face (0,1,2,3) must be CCW when viewed from outside
                # Cross product (c1-c0) × (c3-c0) should point in same direction as (c4-c0)
                e01 = c[1] - c[0]
                e03 = c[3] - c[0]
                normal = np.cross(e01, e03)
                e04 = c[4] - c[0]
                if np.dot(normal, e04) < 0:
                    # Flip bottom face winding: swap 1↔3, 5↔7
                    c = [c[0], c[3], c[2], c[1], c[4], c[7], c[6], c[5]]

                for corner in c:
                    all_vertices.append(np.array([float(corner[0]), float(corner[1]), float(corner[2])]))
                v = vertex_offset
                all_blocks_def.append({
                    "vertices": list(range(v, v + 8)),
                    "cells": [ni - 1, nj - 1, nk - 1],
                    "grading": [1, 1, 1],
                })
                vertex_offset += 8
            else:
                for c in corners_2d:
                    all_vertices.append(c)
                v = vertex_offset
                all_blocks_def.append({
                    "vertices": list(range(v, v + len(corners_2d))),
                    "cells": [ni - 1, nj - 1, 1],
                    "grading": [1, 1, 1],
                })
                vertex_offset += len(corners_2d)

        all_patches = [
            {"name": n, "type": info["type"], "faces": info["faces"]}
            for n, info in patch_map.items()
        ]

        # Merge coincident vertices so blocks share face vertices.
        # blockMesh requires shared vertex indices for inter-block connectivity.
        # Special handling for "wall" (blade) patches: two vertices on blade
        # patches should NOT merge with each other (the blade wall must remain
        # a boundary, not become an internal face). But a blade vertex CAN merge
        # with a non-blade vertex at the same location (inlet/outlet connections).
        vertices_array = np.array(all_vertices, dtype=np.float64)
        n_verts = len(vertices_array)
        tol = 1e-10 * max(np.ptp(vertices_array[:, 0]),
                          np.ptp(vertices_array[:, 1]),
                          np.ptp(vertices_array[:, 2]),
                          1e-15)

        # Identify which block each vertex belongs to (for blade-pair detection)
        vertex_block = {}  # vertex_id → block_index
        for bi, bdef in enumerate(all_blocks_def):
            for vid in bdef["vertices"]:
                vertex_block[vid] = bi

        # Identify vertices on wall patches per block
        wall_verts_by_block: dict[int, set] = {}
        for patch_info in patch_map.values():
            if patch_info["type"] == "wall":
                for face in patch_info["faces"]:
                    for vid in face:
                        bi = vertex_block.get(vid, -1)
                        wall_verts_by_block.setdefault(bi, set()).add(vid)

        # Build mapping: old_index → new_index
        # Don't merge two vertices if both are wall vertices on different blocks
        # (that would make the blade face internal instead of a boundary)
        remap = list(range(n_verts))
        for i in range(n_verts):
            if remap[i] != i:
                continue
            bi_i = vertex_block.get(i, -1)
            i_is_wall = i in wall_verts_by_block.get(bi_i, set())
            for j in range(i + 1, n_verts):
                if remap[j] != j:
                    continue
                if np.linalg.norm(vertices_array[i] - vertices_array[j]) >= tol:
                    continue
                bj_j = vertex_block.get(j, -1)
                j_is_wall = j in wall_verts_by_block.get(bj_j, set())
                # Skip merge only if BOTH are wall vertices on different blocks
                if i_is_wall and j_is_wall and bi_i != bj_j:
                    continue
                remap[j] = i

        # Build compacted vertex list
        unique_ids = sorted(set(remap))
        new_idx = {old: new for new, old in enumerate(unique_ids)}
        final_remap = [new_idx[remap[i]] for i in range(n_verts)]

        merged_vertices = vertices_array[unique_ids]

        # Remap all references
        for bdef in all_blocks_def:
            bdef["vertices"] = [final_remap[v] for v in bdef["vertices"]]
        for patch in all_patches:
            patch["faces"] = [
                [final_remap[v] for v in face] for face in patch["faces"]
            ]
        for edge in all_edges:
            edge["v0"] = final_remap[edge["v0"]]
            edge["v1"] = final_remap[edge["v1"]]

        write_blockmeshdict(filepath, merged_vertices, all_blocks_def, all_patches,
                            edges=all_edges)

    def _export_openfoam_o10h(self, filepath: str | Path, z_thickness: float) -> None:
        """Export O10H topology mesh directly to blockMeshDict.

        Uses the stored O10H vertex/block/patch data to generate the
        blockMeshDict with proper vertex sharing, 16 hex blocks, and
        polyLine curved edges for the blade profile and O-grid outer.

        This avoids the generic per-block export which cannot correctly
        share vertices between the 16 blocks of the O10H topology.
        """
        from ..export.openfoam_writer import write_blockmeshdict

        data = self.o10h_data
        verts_2d = data["vertices"]        # (26, 2)
        block_defs = data["block_defs"]    # list of ([v0,v1,v2,v3], name)
        block_cells = data["block_cells"]  # list of (ni, nj, gi, gj)
        block_patches = data["block_patches"]
        curves = data["curved_edges"]

        n_verts_2d = len(verts_2d)

        # Extrude to 3D: 26 vertices at z=0, 26 at z=z_thickness = 52 total
        vertices_3d = np.zeros((2 * n_verts_2d, 3))
        for i in range(n_verts_2d):
            vertices_3d[i] = [verts_2d[i, 0], verts_2d[i, 1], 0.0]
            vertices_3d[i + n_verts_2d] = [verts_2d[i, 0], verts_2d[i, 1], z_thickness]

        # Define 16 hex blocks
        # Each block's bottom face (z=0) has 4 vertices [v0,v1,v2,v3],
        # top face (z=z_t) has [v0+26, v1+26, v2+26, v3+26].
        # OpenFOAM hex ordering: (v0 v1 v2 v3 v4 v5 v6 v7) where
        # v0-v3 = bottom face (CCW from outside), v4-v7 = top face.
        nv = n_verts_2d  # offset for z=z_t layer

        all_blocks = []
        for bi, (vidxs, bname) in enumerate(block_defs):
            v0, v1, v2, v3 = vidxs
            ni_cells, nj_cells, gi, gj = block_cells[bi]

            # Check if block needs flipping (CW → CCW for OpenFOAM).
            p = [verts_2d[v0], verts_2d[v1], verts_2d[v2], verts_2d[v3]]
            signed_area = sum(
                p[k][0] * p[(k+1)%4][1] - p[(k+1)%4][0] * p[k][1]
                for k in range(4)
            ) * 0.5

            if signed_area >= 0:
                # Already CCW -- no flip needed
                hex_verts = [v0, v1, v2, v3, v0+nv, v1+nv, v2+nv, v3+nv]
                cell_counts = [ni_cells, nj_cells, 1]
                grading_vals = [gi, gj, 1]
            else:
                # CW -- flip to CCW by reversing: v0, v3, v2, v1
                hex_verts = [v0, v3, v2, v1, v0+nv, v3+nv, v2+nv, v1+nv]
                # Flipping swaps i↔j directions, so swap cell counts and grading
                cell_counts = [nj_cells, ni_cells, 1]
                grading_vals = [gj, gi, 1]

            all_blocks.append({
                "vertices": hex_verts,
                "cells": cell_counts,
                "grading": grading_vals,
                "_flipped": signed_area < 0,  # track for face mapping
            })

        # ── Patch definitions ──
        _of_type = {
            "blade": "wall", "inlet": "patch", "outlet": "patch",
            "periodic_upper": "cyclic", "periodic_lower": "cyclic",
        }

        patch_map: dict[str, dict] = {}

        # frontAndBack (z=0 and z=z_t faces of all 16 blocks)
        patch_map["frontAndBack"] = {"type": "empty", "faces": []}

        for bi, (vidxs, bname) in enumerate(block_defs):
            v0, v1, v2, v3 = vidxs
            flipped = all_blocks[bi].get("_flipped", False)

            # z-faces
            if flipped:
                patch_map["frontAndBack"]["faces"].append([v0, v1, v2, v3])
                patch_map["frontAndBack"]["faces"].append(
                    [v0+nv, v3+nv, v2+nv, v1+nv])
            else:
                patch_map["frontAndBack"]["faces"].append([v0, v3, v2, v1])
                patch_map["frontAndBack"]["faces"].append(
                    [v0+nv, v1+nv, v2+nv, v3+nv])

            if flipped:
                # Flipped hex: [v0,v3,v2,v1]. Face mapping:
                # original "bottom" (v0→v1) → hex edge fv0→fv3 = face_left in hex
                # original "top" (v3→v2) → hex edge fv1→fv2 = face_right in hex
                # original "left" (v0→v3) → hex edge fv0→fv1 = face_bottom in hex
                # original "right" (v1→v2) → hex edge fv3→fv2 = face_top in hex
                face_defs = {
                    "bottom": [v0, v0+nv, v1+nv, v1],   # v0→v1 (original bottom)
                    "top": [v3, v2, v2+nv, v3+nv],       # v3→v2 (original top)
                    "left": [v0, v3, v3+nv, v0+nv],      # v0→v3 (original left)
                    "right": [v1, v1+nv, v2+nv, v2],     # v1→v2 (original right)
                }
            else:
                # Normal hex: [v0,v1,v2,v3]. Direct mapping.
                face_defs = {
                    "bottom": [v0, v1, v1+nv, v0+nv],
                    "top": [v3, v3+nv, v2+nv, v2],
                    "left": [v0, v0+nv, v3+nv, v3],
                    "right": [v1, v2, v2+nv, v1+nv],
                }

            for face_name, boundary_name in block_patches[bi].items():
                if face_name in face_defs:
                    of_type = _of_type.get(boundary_name, "patch")
                    if boundary_name not in patch_map:
                        patch_map[boundary_name] = {"type": of_type, "faces": []}
                    patch_map[boundary_name]["faces"].append(face_defs[face_name])

        all_patches = [
            {"name": n, "type": info["type"], "faces": info["faces"]}
            for n, info in patch_map.items()
        ]

        # ── PolyLine curved edges ──
        all_edges = []

        # Map: (start_vertex, end_vertex) → curve points
        # Profile edges (blade surface)
        edge_curves = {
            (6, 12): curves["ss_le_profile"],    # suction LE→mid
            (12, 18): curves["ss_te_profile"],   # suction mid→TE
            (7, 13): curves["ps_le_profile"],    # pressure LE→mid
            (13, 19): curves["ps_te_profile"],   # pressure mid→TE
            # O-grid outer edges
            (5, 11): curves["ss_le_ogrid"],
            (11, 17): curves["ss_te_ogrid"],
            (8, 14): curves["ps_le_ogrid"],
            (14, 20): curves["ps_te_ogrid"],
            # LE/TE cap edges omitted -- the cap blocks use straight edges
            # between their vertices, which is sufficient for blockMesh quality.
            # Curved cap edges cause negative-volume cells at high curvature.
        }

        for (va, vb), pts_2d in edge_curves.items():
            if len(pts_2d) < 3:
                continue
            # Check if edge is significantly curved
            p0 = pts_2d[0]
            p1 = pts_2d[-1]
            line_dir = p1 - p0
            line_len = np.linalg.norm(line_dir)
            if line_len < 1e-15:
                continue
            line_dir_n = line_dir / line_len
            deviations = np.abs(
                (pts_2d[1:-1, 0] - p0[0]) * (-line_dir_n[1]) +
                (pts_2d[1:-1, 1] - p0[1]) * line_dir_n[0]
            )
            max_dev = np.max(deviations) if len(deviations) > 0 else 0.0

            if max_dev > 0.001 * line_len:
                # Subsample intermediate points
                n_pts = len(pts_2d)
                if n_pts > 22:
                    indices = np.linspace(1, n_pts - 2, 20, dtype=int)
                    intermediate = pts_2d[indices]
                else:
                    intermediate = pts_2d[1:-1]

                if len(intermediate) == 0:
                    continue

                # z=0 layer
                pts_3d_z0 = np.column_stack([
                    intermediate[:, 0], intermediate[:, 1],
                    np.zeros(len(intermediate))
                ])
                all_edges.append({"v0": va, "v1": vb, "points": pts_3d_z0})

                # z=z_t layer
                pts_3d_zt = np.column_stack([
                    intermediate[:, 0], intermediate[:, 1],
                    np.full(len(intermediate), z_thickness)
                ])
                all_edges.append({"v0": va + nv, "v1": vb + nv, "points": pts_3d_zt})

        write_blockmeshdict(filepath, vertices_3d, all_blocks, all_patches,
                            edges=all_edges)


class MultiBlockGenerator:
    """Generates multi-block structured meshes from polyline boundaries.

    This is the native Python replacement for GridZ. The workflow:
    1. Define blocks by their 4 boundary polylines (bottom, top, left, right)
    2. Apply grading to each edge
    3. Generate interior points via transfinite interpolation
    4. Assemble into a MultiBlockMesh
    5. Export to CGNS or OpenFOAM

    Usage::

        gen = MultiBlockGenerator()
        gen.add_block("inlet", bottom, top, left, right,
                      n_i=20, n_j=15, grading_i=0.5)
        gen.add_block("blade", bottom2, top2, left2, right2,
                      n_i=40, n_j=15, grading_j=1.3)
        mesh = gen.generate()
        mesh.export_cgns("output.cgns")
    """

    def __init__(self) -> None:
        self._block_defs: list[dict] = []

    def add_block(
        self,
        name: str,
        bottom: Polyline | NDArray[np.float64],
        top: Polyline | NDArray[np.float64],
        left: Polyline | NDArray[np.float64],
        right: Polyline | NDArray[np.float64],
        n_i: int = 20,
        n_j: int = 20,
        grading_i: float = 1.0,
        grading_j: float = 1.0,
        patches: dict[str, str] | None = None,
    ) -> None:
        """Add a block definition.

        Args:
            name: Block name.
            bottom: Bottom boundary (i-direction, j=0).
            top: Top boundary (i-direction, j=max).
            left: Left boundary (j-direction, i=0).
            right: Right boundary (j-direction, i=max).
            n_i: Number of cells in i-direction.
            n_j: Number of cells in j-direction.
            grading_i: Grading ratio in i-direction.
            grading_j: Grading ratio in j-direction.
            patches: Dict mapping face names to boundary types.
        """
        def _to_polyline(data):
            if isinstance(data, Polyline):
                return data
            return Polyline(np.asarray(data, dtype=np.float64))

        self._block_defs.append({
            "name": name,
            "bottom": _to_polyline(bottom),
            "top": _to_polyline(top),
            "left": _to_polyline(left),
            "right": _to_polyline(right),
            "n_i": n_i,
            "n_j": n_j,
            "grading_i": grading_i,
            "grading_j": grading_j,
            "patches": patches or {},
        })

    def add_block_from_topology(
        self,
        name: str,
        topology: BlockTopology,
        edge_bottom: int,
        edge_top: int,
        edge_left: int,
        edge_right: int,
        n_i: int = 20,
        n_j: int = 20,
        grading_i: float = 1.0,
        grading_j: float = 1.0,
    ) -> None:
        """Add a block using edge indices from a BlockTopology."""
        edges = topology.edges
        self.add_block(
            name=name,
            bottom=edges[edge_bottom].to_polyline(),
            top=edges[edge_top].to_polyline(),
            left=edges[edge_left].to_polyline(),
            right=edges[edge_right].to_polyline(),
            n_i=n_i, n_j=n_j,
            grading_i=grading_i, grading_j=grading_j,
        )

    def generate(self) -> MultiBlockMesh:
        """Generate the multi-block structured mesh.

        For each block:
        1. Resample boundary polylines to required point counts with grading
        2. Run transfinite interpolation
        3. Assemble into StructuredBlock

        Returns:
            MultiBlockMesh ready for export.
        """
        mesh = MultiBlockMesh()

        for bdef in self._block_defs:
            ni = bdef["n_i"] + 1  # Points = cells + 1
            nj = bdef["n_j"] + 1

            # Resample boundaries with grading
            t_i = compute_graded_parameters(ni, bdef["grading_i"])
            t_j = compute_graded_parameters(nj, bdef["grading_j"])

            bottom = self._resample_at(bdef["bottom"], t_i)
            top = self._resample_at(bdef["top"], t_i)
            left = self._resample_at(bdef["left"], t_j)
            right = self._resample_at(bdef["right"], t_j)

            # TFI
            points = tfi_2d_vectorized(bottom, top, left, right)

            block = StructuredBlock(
                name=bdef["name"],
                points=points,
                n_cells_i=bdef["n_i"],
                n_cells_j=bdef["n_j"],
                grading_i=bdef["grading_i"],
                grading_j=bdef["grading_j"],
                patches=bdef["patches"],
            )
            mesh.blocks.append(block)

        return mesh

    @staticmethod
    def _resample_at(
        polyline: Polyline, t_params: NDArray[np.float64]
    ) -> NDArray[np.float64]:
        """Resample a polyline at given normalized parameters."""
        params = polyline.normalized_parameters()
        n = len(t_params)
        dim = polyline.dim
        new_pts = np.empty((n, dim), dtype=np.float64)
        for d in range(dim):
            new_pts[:, d] = np.interp(t_params, params, polyline.points[:, d])
        return new_pts


def _offset_curve(
    pts: NDArray[np.float64], thickness: float, outward_sign: float = 1.0,
) -> NDArray[np.float64]:
    """Spline-smoothed normal offset for O-grid outer boundary.

    Ported from BladeDesigner v1 nurbsToolSet.computeScaledCurve():
    1. Compute raw point-by-point normal offsets with curvature limiting
    2. Fit a smooth cubic spline through the raw offset points
    3. Resample at original parameter values → smooth, non-self-intersecting

    Args:
        pts: (N, 2) ordered curve points.
        thickness: Offset distance (m).
        outward_sign: +1.0 for left-normal offset (suction side),
                      -1.0 for right-normal offset (pressure side).

    Returns:
        (N, 2) smooth offset curve points.
    """
    from scipy.interpolate import CubicSpline

    n = len(pts)
    if n < 3:
        return pts.copy()

    # Compute normals (left-perpendicular to tangent, scaled by sign)
    normals = np.zeros_like(pts)
    for i in range(n):
        ip = min(i + 1, n - 1)
        im = max(i - 1, 0)
        tangent = pts[ip] - pts[im]
        normals[i] = outward_sign * np.array([-tangent[1], tangent[0]])
        nl = np.linalg.norm(normals[i])
        if nl > 1e-15:
            normals[i] /= nl

    # Curvature-limited offset magnitude
    local_offset = np.full(n, thickness)
    for i in range(1, n - 1):
        ds_prev = np.linalg.norm(pts[i] - pts[i - 1])
        ds_next = np.linalg.norm(pts[i + 1] - pts[i])
        ds = 0.5 * (ds_prev + ds_next)
        if ds > 1e-15:
            t_prev = (pts[i] - pts[i - 1])
            t_next = (pts[i + 1] - pts[i])
            t_prev = t_prev / (np.linalg.norm(t_prev) + 1e-15)
            t_next = t_next / (np.linalg.norm(t_next) + 1e-15)
            dtheta = np.arccos(np.clip(np.dot(t_prev, t_next), -1, 1))
            kappa = dtheta / ds
            if kappa > 1e-6:
                r_local = 1.0 / kappa
                local_offset[i] = max(min(thickness, 0.8 * r_local),
                                      0.3 * thickness)

    # Raw offset points
    raw_offset = pts + normals * local_offset[:, np.newaxis]

    # Fit cubic spline through raw offset points parametrized by
    # cumulative arc length of the ORIGINAL curve (not the offset).
    # This ensures the spline follows the blade shape faithfully.
    arc = _arc_length_param(pts)

    # Spline fit and resample → smooth curve
    cs_x = CubicSpline(arc, raw_offset[:, 0], bc_type='not-a-knot')
    cs_y = CubicSpline(arc, raw_offset[:, 1], bc_type='not-a-knot')

    smooth = np.column_stack([cs_x(arc), cs_y(arc)])
    return smooth


def _arc_length_param(pts: NDArray[np.float64]) -> NDArray[np.float64]:
    """Compute normalized arc-length parameters for a curve.

    Args:
        pts: (N, 2) curve points.

    Returns:
        (N,) array of normalized arc-length parameters in [0, 1].
    """
    dists = np.sqrt(np.sum(np.diff(pts, axis=0) ** 2, axis=1))
    cum = np.zeros(len(pts))
    cum[1:] = np.cumsum(dists)
    total = cum[-1]
    if total > 1e-15:
        cum /= total
    else:
        cum = np.linspace(0, 1, len(pts))
    return cum


def _interp_curve_at(
    pts: NDArray[np.float64], u: float
) -> NDArray[np.float64]:
    """Interpolate a curve at a normalized arc-length parameter.

    Args:
        pts: (N, 2) curve points.
        u: Normalized arc-length parameter in [0, 1].

    Returns:
        (2,) interpolated point.
    """
    params = _arc_length_param(pts)
    x = np.interp(u, params, pts[:, 0])
    y = np.interp(u, params, pts[:, 1])
    return np.array([x, y])


def _subcurve(
    pts: NDArray[np.float64], u_start: float, u_end: float, n_pts: int = 30
) -> NDArray[np.float64]:
    """Extract a subcurve between two arc-length parameters.

    Args:
        pts: (N, 2) curve points.
        u_start: Start arc-length parameter.
        u_end: End arc-length parameter.
        n_pts: Number of points in the subcurve.

    Returns:
        (n_pts, 2) subcurve points.
    """
    params = _arc_length_param(pts)
    u_vals = np.linspace(u_start, u_end, n_pts)
    result = np.zeros((n_pts, 2))
    result[:, 0] = np.interp(u_vals, params, pts[:, 0])
    result[:, 1] = np.interp(u_vals, params, pts[:, 1])
    return result


def _calculate_u_from_x(
    pts: NDArray[np.float64], x_target: float
) -> float:
    """Find arc-length parameter where curve has a given x-coordinate.

    Ported from BladeDesigner v1 calculateUFromZ(). For each half-profile
    (suction or pressure side), x is monotonically increasing from LE to TE,
    so np.interp gives a unique result.

    Args:
        pts: (N, 2) curve points (must be monotonic in x).
        x_target: Target x-coordinate.

    Returns:
        Normalized arc-length parameter u in [0, 1].
    """
    params = _arc_length_param(pts)
    x_vals = pts[:, 0]

    # Clip target to curve range
    x_target = np.clip(x_target, x_vals.min(), x_vals.max())

    # Check monotonicity direction and interpolate
    if x_vals[-1] >= x_vals[0]:
        # x increasing (normal: LE to TE)
        return float(np.interp(x_target, x_vals, params))
    else:
        # x decreasing (reversed curve) -- flip for interp
        return float(np.interp(x_target, x_vals[::-1], params[::-1]))


def generate_blade_passage_mesh(
    profile: NDArray[np.float64],
    pitch: float,
    n_blade: int = 40,
    n_ogrid: int = 10,
    n_inlet: int = 15,
    n_outlet: int = 15,
    n_passage: int = 20,
    ogrid_thickness: float = 0.01,
    grading_ogrid: float = 1.3,
    grading_inlet: float = 0.5,
    grading_outlet: float = 2.0,
    inlet_offset: float | None = None,
    outlet_offset: float | None = None,
) -> MultiBlockMesh:
    """Generate a blade passage mesh using O10H topology (26 vertices, 16 blocks).

    Creates an O-grid around the blade with H-grid passage blocks, using the
    O10H multi-block topology ported from BladeDesigner v1. The topology has
    6 key stations along the blade (TE-suction, mid-suction, LE-suction,
    LE-pressure, mid-pressure, TE-pressure) and forms a proper O-grid with
    LE and TE cap blocks.

    Block topology (schematic)::

        Inlet     |  LE region  | Mid-chord  |  TE region  | Outlet
        +---------+------+------+------+------+------+------+---------+
        |  blk 0  | blk3 |      | blk8 |      | blk13|  upper row
        +---------+------+ blk4 +------+ blk9 +------+---------+
        |  blk 1  | blk5 |======| blk10|======| blk14|  O-grid row
        +---------+------+ blk6 +------+ blk11+------+---------+
        |  blk 2  | blk7 |      | blk12|      | blk15|  lower row
        +---------+------+------+------+------+------+---------+
                   === blade wall ===

    Args:
        profile: (N, 2) closed blade profile (physical coordinates).
        pitch: Blade-to-blade pitch (m).
        n_blade: Cells along blade per surface half (LE-to-mid and mid-to-TE).
        n_ogrid: Cells in O-grid wall-normal direction.
        n_inlet: Cells in inlet block (streamwise).
        n_outlet: Cells in outlet block (streamwise).
        n_passage: Cells in pitchwise direction (between O-grid and periodic).
        ogrid_thickness: O-grid layer thickness (m). Auto-capped at LE radius.
        grading_ogrid: O-grid wall-normal grading ratio.
        grading_inlet: Inlet block streamwise grading.
        grading_outlet: Outlet block streamwise grading.
        inlet_offset: Distance upstream of LE (default: 0.5 * chord).
        outlet_offset: Distance downstream of TE (default: 0.5 * chord).

    Returns:
        MultiBlockMesh ready for export to CGNS or OpenFOAM.
    """
    _logger = logging.getLogger(__name__)

    # ── Profile analysis ──
    le_idx = int(np.argmin(profile[:, 0]))
    x_min, x_max = profile[:, 0].min(), profile[:, 0].max()
    chord = x_max - x_min
    y_mid = profile[:, 1].mean()

    if inlet_offset is None:
        inlet_offset = 0.5 * chord
    if outlet_offset is None:
        outlet_offset = 0.5 * chord

    x_inlet = x_min - inlet_offset
    x_outlet = x_max + outlet_offset
    y_lower = y_mid - pitch / 2
    y_upper = y_mid + pitch / 2

    # Split profile into suction side (LE→TE, upper) and pressure side (LE→TE, lower).
    # Convention: profile goes TE → suction → LE → pressure → TE
    # So profile[:le_idx+1] is TE→LE on suction side; reversed = LE→TE suction.
    suction_raw = profile[:le_idx + 1][::-1]   # LE → TE suction
    pressure_raw = profile[le_idx:]              # LE → TE pressure

    # ── O-grid outer boundary ──
    # Compute offset curves on each half-profile separately. Each half
    # (suction LE→TE, pressure LE→TE) has outward-pointing normals.
    # Suction side: left-normal (+1) points away from blade (upward).
    # Pressure side: right-normal (-1) points away from blade (downward).
    suction_outer = _offset_curve(suction_raw, ogrid_thickness, outward_sign=+1.0)
    pressure_outer = _offset_curve(pressure_raw, ogrid_thickness, outward_sign=-1.0)

    # ── Vertex placement using axial (x-coordinate) matching ──
    # Ported from BladeDesigner v1 uValuesO10H() / calculateUFromZ().
    # Key insight: blade vertex v6 and O-grid vertex v5 share the SAME
    # x-coordinate. This ensures radial O-grid edges are perpendicular
    # to the flow direction, and cap blocks form valid convex quads.
    x_le_station = x_min + 0.25 * chord    # 25% chord from LE
    x_mid = 0.5 * (x_min + x_max)          # mid-chord
    x_te_station = x_min + 0.75 * chord    # 75% chord from LE

    # Compute per-curve u-parameters at each x-station.
    # For the 4 SURFACE blocks (not caps), blade and ogrid vertices share
    # the same x-coordinate (axial matching from BladeDesigner v1).
    # For the 2 CAP blocks (LE/TE), ogrid vertices use arc-length matching
    # instead, so they sit slightly upstream/downstream of the blade vertices,
    # forming non-degenerate cap quads.
    u_le_ss = _calculate_u_from_x(suction_raw, x_le_station)
    u_mid_ss = _calculate_u_from_x(suction_raw, x_mid)
    u_te_ss = _calculate_u_from_x(suction_raw, x_te_station)

    u_le_ps = _calculate_u_from_x(pressure_raw, x_le_station)
    u_mid_ps = _calculate_u_from_x(pressure_raw, x_mid)
    u_te_ps = _calculate_u_from_x(pressure_raw, x_te_station)

    # Mid-chord ogrid vertices use x-matching (they're on surface blocks, not caps)
    u_mid_ss_o = _calculate_u_from_x(suction_outer, x_mid)
    u_mid_ps_o = _calculate_u_from_x(pressure_outer, x_mid)

    # LE/TE ogrid vertices: use arc-length matching from blade u-parameters.
    # The ogrid outer curve is longer than the blade curve near LE/TE,
    # so the same arc-length fraction puts the ogrid vertex slightly
    # upstream at LE and downstream at TE -- exactly what we need for
    # non-degenerate cap blocks.
    u_le_ss_o = u_le_ss      # same arc-length fraction on ogrid outer
    u_le_ps_o = u_le_ps
    u_te_ss_o = u_te_ss
    u_te_ps_o = u_te_ps

    # Profile key points (on blade surface)
    v6 = _interp_curve_at(suction_raw, u_le_ss)     # LE suction
    v12 = _interp_curve_at(suction_raw, u_mid_ss)    # mid-chord suction
    v18 = _interp_curve_at(suction_raw, u_te_ss)     # TE suction
    v7 = _interp_curve_at(pressure_raw, u_le_ps)     # LE pressure
    v13 = _interp_curve_at(pressure_raw, u_mid_ps)    # mid-chord pressure
    v19 = _interp_curve_at(pressure_raw, u_te_ps)     # TE pressure

    # O-grid outer key points (matched by x-coordinate)
    v5 = _interp_curve_at(suction_outer, u_le_ss_o)
    v11 = _interp_curve_at(suction_outer, u_mid_ss_o)
    v17 = _interp_curve_at(suction_outer, u_te_ss_o)
    v8 = _interp_curve_at(pressure_outer, u_le_ps_o)
    v14 = _interp_curve_at(pressure_outer, u_mid_ps_o)
    v20 = _interp_curve_at(pressure_outer, u_te_ps_o)

    # ── Domain boundary points ──
    x_le_region = x_le_station
    x_te_region = x_te_station

    # 26 vertices
    verts = np.zeros((26, 2))

    # Inlet boundary (4 points)
    verts[0] = [x_inlet, y_upper]
    verts[1] = [x_inlet, v5[1]]      # match O-grid LE suction y
    verts[2] = [x_inlet, v8[1]]      # match O-grid LE pressure y
    verts[3] = [x_inlet, y_lower]

    # LE station passage
    verts[4] = [x_le_region, y_upper]
    verts[9] = [x_le_region, y_lower]

    # O-grid outer at LE
    verts[5] = v5
    verts[8] = v8

    # Blade profile at LE
    verts[6] = v6
    verts[7] = v7

    # Mid-chord passage
    verts[10] = [x_mid, y_upper]
    verts[15] = [x_mid, y_lower]

    # O-grid outer at mid-chord
    verts[11] = v11
    verts[14] = v14

    # Blade profile at mid-chord
    verts[12] = v12
    verts[13] = v13

    # TE station passage
    verts[16] = [x_te_region, y_upper]
    verts[21] = [x_te_region, y_lower]

    # O-grid outer at TE
    verts[17] = v17
    verts[20] = v20

    # Blade profile at TE
    verts[18] = v18
    verts[19] = v19

    # Outlet boundary (4 points)
    verts[22] = [x_outlet, y_upper]
    verts[23] = [x_outlet, v17[1]]    # match O-grid TE suction y
    verts[24] = [x_outlet, v20[1]]    # match O-grid TE pressure y
    verts[25] = [x_outlet, y_lower]

    # ── 16 block definitions (vertex index quads for bottom face of hex) ──
    block_defs = [
        # Inlet blocks (3)
        ([0, 4, 5, 1],   "inlet_upper"),       # 0
        ([1, 5, 8, 2],   "inlet_middle"),       # 1
        ([2, 8, 9, 3],   "inlet_lower"),        # 2
        # LE-to-midchord (5)
        ([4, 10, 11, 5],  "passage_upper_le"),  # 3
        ([5, 11, 12, 6],  "ogrid_suction_le"),  # 4  blade at bottom
        ([5, 6, 7, 8],    "ogrid_le_cap"),       # 5  blade at 6-7 edge
        ([7, 13, 14, 8],  "ogrid_pressure_le"),  # 6  blade at bottom (7 side)
        ([8, 14, 15, 9],  "passage_lower_le"),  # 7
        # Midchord-to-TE (5)
        ([10, 16, 17, 11], "passage_upper_te"),  # 8
        ([11, 17, 18, 12], "ogrid_suction_te"),  # 9  blade at bottom
        ([17, 18, 19, 20], "ogrid_te_cap"),       # 10 ogrid-ss → blade-ss → blade-ps → ogrid-ps (same as LE cap pattern)
        ([13, 19, 20, 14], "ogrid_pressure_te"),  # 11 blade at bottom (13 side)
        ([14, 20, 21, 15], "passage_lower_te"),  # 12
        # Outlet blocks (3)
        ([16, 22, 23, 17], "outlet_upper"),      # 13
        ([17, 23, 24, 20], "outlet_middle"),     # 14
        ([20, 24, 25, 21], "outlet_lower"),      # 15
    ]

    # ── Cell counts and grading for each block ──
    # Ported from BladeDesigner v1 computeBlockDataO10H() lines 630-676.
    # Grading conventions (from v1):
    #   - axial grading: inlet(grading_inlet), blade(1.0), outlet(grading_outlet)
    #   - circumferential grading: passage sides(1.0), O-grid center(1.0)
    #   - O-grid wall-normal: grading_ogrid (blade→outer direction)
    #   - Pressure-side O-grid blocks (6,11): use 1/grading_ogrid (inverted)
    #     because the v0→v3 direction runs from outer→blade (opposite)
    n_half = n_blade  # cells per half blade (LE-to-mid, mid-to-TE)
    n_pw = n_passage  # pitchwise cells
    n_le_cap = max(n_ogrid, 4)  # cells across LE cap

    g_in = grading_inlet    # streamwise grading at inlet
    g_out = grading_outlet  # streamwise grading at outlet
    g_og = grading_ogrid    # O-grid wall-normal (blade→outer)
    g_og_inv = 1.0 / grading_ogrid if grading_ogrid > 1e-10 else 1.0

    block_cells = [
        # (n_i, n_j, grading_i, grading_j)
        # Grading is set to 1.0 (uniform) because simpleGrading cannot
        # consistently handle the i↔j swap from winding flips across
        # shared faces. The v1 BladeDesigner uses edgeGrading (12 values
        # per hex) which avoids this issue. TODO: port v1 edgeGrading.
        (n_inlet,  n_pw,      1.0, 1.0),           # 0: inlet upper
        (n_inlet,  n_ogrid,   1.0, 1.0),           # 1: inlet middle
        (n_inlet,  n_pw,      1.0, 1.0),           # 2: inlet lower
        (n_half,   n_pw,      1.0, 1.0),           # 3: passage upper LE
        (n_half,   n_ogrid,   1.0, 1.0),           # 4: O-grid suction LE
        (n_le_cap, n_ogrid,   1.0, 1.0),           # 5: O-grid LE cap
        (n_half,   n_ogrid,   1.0, 1.0),           # 6: O-grid pressure LE
        (n_half,   n_pw,      1.0, 1.0),           # 7: passage lower LE
        (n_half,   n_pw,      1.0, 1.0),           # 8: passage upper TE
        (n_half,   n_ogrid,   1.0, 1.0),           # 9: O-grid suction TE
        (n_le_cap, n_ogrid,   1.0, 1.0),           # 10: O-grid TE cap
        (n_half,   n_ogrid,   1.0, 1.0),           # 11: O-grid pressure TE
        (n_half,   n_pw,      1.0, 1.0),           # 12: passage lower TE
        (n_outlet, n_pw,      1.0, 1.0),           # 13: outlet upper
        (n_outlet, n_ogrid,   1.0, 1.0),           # 14: outlet middle
        (n_outlet, n_pw,      1.0, 1.0),           # 15: outlet lower
    ]

    # ── Patch assignments ──
    # Computed from vertex positions: edge (va,vb) belongs to a boundary
    # if both vertices are in the boundary vertex set.
    # Keys: "bottom"=v0→v1, "top"=v3→v2, "left"=v0→v3, "right"=v1→v2
    block_patches = [
        {"bottom": "periodic_upper", "left": "inlet"},  # 0: inlet_upper
        {"left": "inlet"},                                # 1: inlet_middle
        {"top": "periodic_lower", "left": "inlet"},      # 2: inlet_lower
        {"bottom": "periodic_upper"},                     # 3: passage_upper_le
        {"top": "blade"},                                 # 4: ogrid_suction_le
        {"right": "blade"},                               # 5: ogrid_le_cap
        {"bottom": "blade"},                              # 6: ogrid_pressure_le
        {"top": "periodic_lower"},                        # 7: passage_lower_le
        {"bottom": "periodic_upper"},                     # 8: passage_upper_te
        {"top": "blade"},                                 # 9: ogrid_suction_te
        {"right": "blade"},                               # 10: ogrid_te_cap
        {"bottom": "blade"},                              # 11: ogrid_pressure_te
        {"top": "periodic_lower"},                        # 12: passage_lower_te
        {"bottom": "periodic_upper", "right": "outlet"}, # 13: outlet_upper
        {"right": "outlet"},                              # 14: outlet_middle
        {"top": "periodic_lower", "right": "outlet"},    # 15: outlet_lower
    ]

    # ── Build TFI blocks for quality metrics / CGNS export ──
    # For each block, construct 4 boundary curves from the vertex corners
    # and the profile/ogrid curves for curved edges.

    # Extract subcurves from profile and ogrid outer for curved block edges
    # Using per-curve u-values from axial-coordinate matching
    ss_le_profile = _subcurve(suction_raw, u_le_ss, u_mid_ss, n_half + 1)      # v6 → v12
    ss_te_profile = _subcurve(suction_raw, u_mid_ss, u_te_ss, n_half + 1)      # v12 → v18
    ps_le_profile = _subcurve(pressure_raw, u_le_ps, u_mid_ps, n_half + 1)     # v7 → v13
    ps_te_profile = _subcurve(pressure_raw, u_mid_ps, u_te_ps, n_half + 1)     # v13 → v19

    ss_le_ogrid = _subcurve(suction_outer, u_le_ss_o, u_mid_ss_o, n_half + 1)  # v5 → v11
    ss_te_ogrid = _subcurve(suction_outer, u_mid_ss_o, u_te_ss_o, n_half + 1)  # v11 → v17
    ps_le_ogrid = _subcurve(pressure_outer, u_le_ps_o, u_mid_ps_o, n_half + 1) # v8 → v14
    ps_te_ogrid = _subcurve(pressure_outer, u_mid_ps_o, u_te_ps_o, n_half + 1) # v14 → v20

    # LE cap: v6 → LE → v7 (suction back to LE, then LE to pressure)
    le_ss_part = _subcurve(suction_raw, 0.0, u_le_ss, n_le_cap // 2 + 1)[::-1]
    le_ps_part = _subcurve(pressure_raw, 0.0, u_le_ps, n_le_cap // 2 + 1)
    le_cap_profile_pts = np.vstack([le_ss_part, le_ps_part[1:]])

    le_ss_ogrid_part = _subcurve(suction_outer, 0.0, u_le_ss_o, n_le_cap // 2 + 1)[::-1]
    le_ps_ogrid_part = _subcurve(pressure_outer, 0.0, u_le_ps_o, n_le_cap // 2 + 1)
    le_cap_ogrid_pts = np.vstack([le_ss_ogrid_part, le_ps_ogrid_part[1:]])

    # TE cap: v18 → TE → v19 (suction to TE, then TE back to pressure)
    te_ss_part = _subcurve(suction_raw, u_te_ss, 1.0, n_le_cap // 2 + 1)
    te_ps_part = _subcurve(pressure_raw, u_te_ps, 1.0, n_le_cap // 2 + 1)
    te_cap_profile_pts = np.vstack([te_ss_part, te_ps_part[::-1][1:]])

    te_ss_ogrid_part = _subcurve(suction_outer, u_te_ss_o, 1.0, n_le_cap // 2 + 1)
    te_ps_ogrid_part = _subcurve(pressure_outer, u_te_ps_o, 1.0, n_le_cap // 2 + 1)
    te_cap_ogrid_pts = np.vstack([te_ss_ogrid_part, te_ps_ogrid_part[::-1][1:]])

    def _make_line(p0, p1, n):
        """Generate n+1 linearly spaced points from p0 to p1."""
        return np.linspace(p0, p1, n + 1)

    mesh = MultiBlockMesh()

    for bi, (vidxs, bname) in enumerate(block_defs):
        ni_cells, nj_cells, gi, gj = block_cells[bi]
        v0, v1, v2, v3 = [verts[k] for k in vidxs]

        # Default: linear edges
        ni = ni_cells + 1
        nj = nj_cells + 1
        bottom = _make_line(v0, v1, ni_cells)  # i-dir, j=0
        top = _make_line(v3, v2, ni_cells)      # i-dir, j=max
        left = _make_line(v0, v3, nj_cells)     # j-dir, i=0
        right = _make_line(v1, v2, nj_cells)    # j-dir, i=max

        # Override with curved edges where applicable
        if bi == 4:  # ogrid_suction_le: bottom=profile v6→v12, top=ogrid v5→v11
            bottom = ss_le_profile
            top = ss_le_ogrid
        elif bi == 5:  # ogrid_le_cap: bottom=v5→v6→v7→v8 as LE cap
            bottom = le_cap_profile_pts
            top = le_cap_ogrid_pts
        elif bi == 6:  # ogrid_pressure_le: bottom=profile v7→v13, top=ogrid v8→v14
            bottom = ps_le_profile
            top = ps_le_ogrid
        elif bi == 9:  # ogrid_suction_te: bottom=profile v12→v18, top=ogrid v11→v17
            bottom = ss_te_profile
            top = ss_te_ogrid
        elif bi == 10:  # ogrid_te_cap: vertices [17, 18, 19, 20]
            # Same pattern as LE cap [5,6,7,8]:
            # bottom (j=0): v17→v18 (ogrid-ss to blade-ss)
            # top (j=max): v20→v19 (ogrid-ps to blade-ps)
            # left (i=0): te_cap_ogrid v17→v20
            # right (i=max): te_cap_profile v18→v19
            left = te_cap_ogrid_pts
            right = te_cap_profile_pts
        elif bi == 11:  # ogrid_pressure_te: bottom=profile v13→v19, top=ogrid v14→v20
            bottom = ps_te_profile
            top = ps_te_ogrid
        elif bi == 3:  # passage_upper_le: bottom=ogrid v5→v11, top=periodic
            bottom = ss_le_ogrid
        elif bi == 7:  # passage_lower_le: bottom=periodic, top=ogrid v8→v14
            top = ps_le_ogrid
        elif bi == 8:  # passage_upper_te: bottom=ogrid v11→v17, top=periodic
            bottom = ss_te_ogrid
        elif bi == 12:  # passage_lower_te: bottom=periodic, top=ogrid v14→v20
            top = ps_te_ogrid

        # Ensure boundary point counts match
        if len(bottom) != ni:
            bottom_orig = bottom
            bottom = np.zeros((ni, 2))
            t_b = np.linspace(0, 1, ni)
            t_o = np.linspace(0, 1, len(bottom_orig))
            bottom[:, 0] = np.interp(t_b, t_o, bottom_orig[:, 0])
            bottom[:, 1] = np.interp(t_b, t_o, bottom_orig[:, 1])
        if len(top) != ni:
            top_orig = top
            top = np.zeros((ni, 2))
            t_b = np.linspace(0, 1, ni)
            t_o = np.linspace(0, 1, len(top_orig))
            top[:, 0] = np.interp(t_b, t_o, top_orig[:, 0])
            top[:, 1] = np.interp(t_b, t_o, top_orig[:, 1])
        if len(left) != nj:
            left_orig = left
            left = np.zeros((nj, 2))
            t_b = np.linspace(0, 1, nj)
            t_o = np.linspace(0, 1, len(left_orig))
            left[:, 0] = np.interp(t_b, t_o, left_orig[:, 0])
            left[:, 1] = np.interp(t_b, t_o, left_orig[:, 1])
        if len(right) != nj:
            right_orig = right
            right = np.zeros((nj, 2))
            t_b = np.linspace(0, 1, nj)
            t_o = np.linspace(0, 1, len(right_orig))
            right[:, 0] = np.interp(t_b, t_o, right_orig[:, 0])
            right[:, 1] = np.interp(t_b, t_o, right_orig[:, 1])

        # Fix corners for consistency
        left[0] = bottom[0]
        left[-1] = top[0]
        right[0] = bottom[-1]
        right[-1] = top[-1]

        points = tfi_2d_vectorized(bottom, top, left, right)

        block = StructuredBlock(
            name=bname,
            points=points,
            n_cells_i=ni_cells,
            n_cells_j=nj_cells,
            grading_i=gi,
            grading_j=gj,
            patches=block_patches[bi],
        )
        mesh.blocks.append(block)

    # ── Store O10H data for direct blockMeshDict generation ──
    mesh.o10h_data = {
        "vertices": verts,
        "block_defs": block_defs,
        "block_cells": block_cells,
        "block_patches": block_patches,
        # Curved edge subcurves (profile and ogrid outer) for polyLine export
        "curved_edges": {
            "ss_le_profile": ss_le_profile,
            "ss_te_profile": ss_te_profile,
            "ps_le_profile": ps_le_profile,
            "ps_te_profile": ps_te_profile,
            "ss_le_ogrid": ss_le_ogrid,
            "ss_te_ogrid": ss_te_ogrid,
            "ps_le_ogrid": ps_le_ogrid,
            "ps_te_ogrid": ps_te_ogrid,
            "le_cap_profile": le_cap_profile_pts,
            "le_cap_ogrid": le_cap_ogrid_pts,
            "te_cap_profile": te_cap_profile_pts,
            "te_cap_ogrid": te_cap_ogrid_pts,
        },
    }

    # Run quality checks and log warnings
    from .quality import mesh_quality_report
    for block in mesh.blocks:
        report = mesh_quality_report(block.points)
        if report.get("aspect_ratio_max", 0) > 100:
            _logger.warning(
                "Block '%s': max aspect ratio %.1f exceeds threshold of 100",
                block.name, report["aspect_ratio_max"],
            )
        if report.get("skewness_max", 0) > 0.95:
            _logger.warning(
                "Block '%s': max skewness %.3f exceeds threshold of 0.95",
                block.name, report["skewness_max"],
            )

    return mesh


def generate_blade_passage_mesh_3d(
    profiles: list[NDArray[np.float64]],
    span_positions: list[float],
    pitch: float,
    n_blade: int = 40,
    n_ogrid: int = 10,
    n_inlet: int = 15,
    n_outlet: int = 15,
    n_passage: int = 20,
    ogrid_thickness: float = 0.01,
    grading_ogrid: float = 1.3,
    grading_inlet: float = 0.5,
    grading_outlet: float = 2.0,
) -> MultiBlockMesh:
    """Generate a 3D blade passage mesh by stacking 2D meshes at span stations.

    Takes 2D profiles at different span stations, generates a 2D mesh at each
    station, then stacks them with interpolation in the span direction.

    Args:
        profiles: List of (N, 2) closed 2D blade profiles at different span stations.
        span_positions: List of span coordinates (z-values) for each profile.
        pitch: Blade-to-blade pitch.
        n_blade: Cells around blade.
        n_ogrid: O-grid cells.
        n_inlet: Inlet cells.
        n_outlet: Outlet cells.
        n_passage: Passage pitchwise cells.
        ogrid_thickness: O-grid layer thickness.
        grading_ogrid: O-grid grading.
        grading_inlet: Inlet grading.
        grading_outlet: Outlet grading.

    Returns:
        MultiBlockMesh with 3D blocks (Ni, Nj, Nk, 3).
    """
    logger = logging.getLogger(__name__)

    if len(profiles) != len(span_positions):
        raise ValueError("Number of profiles must match number of span positions")
    if len(profiles) < 2:
        raise ValueError("At least 2 span stations required for 3D mesh")

    # Generate 2D mesh at each span station
    meshes_2d = []
    for i, profile in enumerate(profiles):
        mesh_2d = generate_blade_passage_mesh(
            profile=profile,
            pitch=pitch,
            n_blade=n_blade,
            n_ogrid=n_ogrid,
            n_inlet=n_inlet,
            n_outlet=n_outlet,
            n_passage=n_passage,
            ogrid_thickness=ogrid_thickness,
            grading_ogrid=grading_ogrid,
            grading_inlet=grading_inlet,
            grading_outlet=grading_outlet,
        )
        meshes_2d.append(mesh_2d)

    # Stack 2D meshes into 3D blocks
    # All meshes should have the same block structure
    n_blocks = meshes_2d[0].n_blocks
    n_span = len(span_positions)

    mesh_3d = MultiBlockMesh(name="AstraTurbo_3D_Mesh")

    for block_idx in range(n_blocks):
        block_name = meshes_2d[0].blocks[block_idx].name
        # Get the 2D block from each span station
        blocks_at_stations = []
        for mesh in meshes_2d:
            if block_idx < len(mesh.blocks):
                blocks_at_stations.append(mesh.blocks[block_idx].points)

        if not blocks_at_stations:
            continue

        ni, nj = blocks_at_stations[0].shape[0], blocks_at_stations[0].shape[1]
        dim_2d = blocks_at_stations[0].shape[2] if blocks_at_stations[0].ndim == 3 else 2

        # Create 3D block: (Ni, Nj, Nk, 3)
        nk = n_span
        block_3d = np.zeros((ni, nj, nk, 3), dtype=np.float64)

        for k, (pts_2d, z_pos) in enumerate(zip(blocks_at_stations, span_positions)):
            block_3d[:, :, k, 0] = pts_2d[:, :, 0] if dim_2d >= 2 else pts_2d[:, :, 0]
            block_3d[:, :, k, 1] = pts_2d[:, :, 1] if dim_2d >= 2 else 0.0
            block_3d[:, :, k, 2] = z_pos

        # If we have fewer mesh stations than span positions, interpolate
        # (for now we require one mesh per span station)

        structured = StructuredBlock(
            name=block_name,
            points=block_3d,
            n_cells_i=ni - 1,
            n_cells_j=nj - 1,
            patches=meshes_2d[0].blocks[block_idx].patches,
        )
        mesh_3d.blocks.append(structured)

    logger.info(
        "Generated 3D mesh: %d blocks, %d total points, %d span stations",
        mesh_3d.n_blocks, mesh_3d.total_points, n_span,
    )
    return mesh_3d
